2025-05-25 02:19:54,054 - INFO - DB connection established
2025-05-25 02:19:54,056 - INFO - DB connection established
2025-05-25 02:19:57,776 - INFO - Attempting to connect to server
2025-05-25 02:19:57,788 - INFO - DB connection established
2025-05-25 02:19:57,789 - INFO - Successfully connected to server
2025-05-25 02:20:01,985 - INFO - DB connection established
2025-05-25 02:20:01,985 - INFO - Generation started for session 14
2025-05-25 02:20:20,900 - INFO - DB connection established
2025-05-25 02:20:20,900 - INFO - Generation stopped
2025-05-25 02:20:23,036 - INFO - Refreshed sessions list, count: 14
2025-05-25 02:20:25,566 - INFO - Loaded 10 packets for session 14
2025-05-25 02:20:30,338 - INFO - DB connection established
2025-05-25 02:20:30,339 - INFO - Disconnected from server during shutdown
2025-05-25 02:20:30,339 - INFO - Disconnected from server
2025-05-25 02:20:30,339 - WARNING - Warning: Соединение с сервером закрыто
2025-05-25 02:20:30,339 - INFO - DB connection closed during shutdown
2025-05-25 02:20:30,340 - INFO - Application shutdown completed
2025-05-25 20:12:07,346 - INFO - DB connection established
2025-05-25 20:12:07,349 - INFO - DB connection established
2025-05-25 20:12:11,867 - INFO - Refreshed sessions list, count: 14
2025-05-25 20:12:14,088 - INFO - Loaded 10 packets for session 14
2025-05-25 20:12:19,333 - INFO - DB connection closed during shutdown
2025-05-25 20:12:19,333 - INFO - Application shutdown completed
2025-05-25 20:43:12,695 - INFO - DB connection established
2025-05-25 20:43:12,696 - INFO - DB connection established
2025-05-25 20:43:17,679 - ERROR - Connection error: HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002EBD18ED520>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-25 20:43:21,752 - INFO - Refreshed sessions list, count: 14
2025-05-25 20:43:22,207 - INFO - Загружено 10 пакетов для сессии 14
2025-05-25 20:43:23,719 - INFO - Загружено 4 пакетов для сессии 13
2025-05-25 20:43:24,183 - INFO - Загружено 4 пакетов для сессии 12
2025-05-25 20:43:24,553 - INFO - Загружено 5 пакетов для сессии 11
2025-05-25 20:43:25,623 - INFO - DB connection closed during shutdown
2025-05-25 20:43:25,623 - INFO - Application shutdown completed
2025-05-25 20:43:43,822 - INFO - DB connection established
2025-05-25 20:43:43,823 - INFO - DB connection established
2025-05-25 20:43:44,560 - INFO - Attempting to connect to server
2025-05-25 20:43:44,607 - INFO - DB connection established
2025-05-25 20:43:44,607 - INFO - Successfully connected to server
2025-05-25 20:43:45,412 - INFO - DB connection established
2025-05-25 20:43:45,412 - INFO - Generation started for session 15
2025-05-25 20:43:53,467 - INFO - DB connection established
2025-05-25 20:43:53,468 - INFO - Generation stopped
2025-05-25 20:43:58,418 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-25 20:43:58,418 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x00000210070FC170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-25 20:43:58,418 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-25 20:43:58,419 - INFO - DB connection established
2025-05-25 20:43:58,420 - INFO - Disconnected from server
2025-05-25 20:43:58,421 - WARNING - Warning: Соединение с сервером закрыто
2025-05-25 20:43:58,421 - INFO - DB connection established
2025-05-25 20:43:58,421 - INFO - Disconnected from server
2025-05-25 20:43:58,422 - WARNING - Warning: Соединение с сервером закрыто
2025-05-25 20:44:04,632 - WARNING - Connection closed Connection is already closed.
2025-05-25 20:44:04,632 - INFO - on_reconnect not defined
2025-05-25 20:44:08,700 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=F6e4DDKr49kjVe7iUkiEsw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000210070FEB70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-25 20:44:14,876 - INFO - DB connection closed during shutdown
2025-05-25 20:44:14,876 - INFO - Application shutdown completed
2025-05-25 20:44:49,965 - INFO - DB connection established
2025-05-25 20:44:49,967 - INFO - DB connection established
2025-05-25 20:44:51,405 - INFO - Attempting to connect to server
2025-05-25 20:44:51,435 - INFO - DB connection established
2025-05-25 20:44:51,435 - INFO - Successfully connected to server
2025-05-25 20:44:52,232 - INFO - DB connection established
2025-05-25 20:44:52,232 - INFO - Generation started for session 16
2025-05-25 20:45:02,220 - INFO - DB connection established
2025-05-25 20:45:02,220 - INFO - Generation stopped
2025-05-25 20:45:05,130 - INFO - Refreshed sessions list, count: 16
2025-05-25 20:45:05,379 - INFO - Загружено 5 пакетов для сессии 16
2025-05-25 20:45:06,172 - INFO - Загружено 4 пакетов для сессии 15
2025-05-25 20:45:06,537 - INFO - Загружено 5 пакетов для сессии 16
2025-05-25 20:45:07,112 - INFO - Загружено 4 пакетов для сессии 15
2025-05-25 20:45:07,477 - INFO - Загружено 5 пакетов для сессии 16
2025-05-25 20:45:27,577 - INFO - DB connection established
2025-05-25 20:45:27,577 - INFO - Disconnected from server
2025-05-25 20:45:27,577 - WARNING - Warning: Соединение с сервером закрыто
2025-05-25 20:45:27,577 - INFO - Disconnected from server during shutdown
2025-05-25 20:45:27,578 - INFO - DB connection closed during shutdown
2025-05-25 20:45:27,578 - INFO - Application shutdown completed
2025-05-26 13:47:27,414 - INFO - Подключение к БД установлено
2025-05-26 13:47:27,417 - INFO - Подключение к БД установлено
2025-05-26 13:47:39,828 - INFO - Список сессий обновлен, количество: 16
2025-05-26 13:47:41,780 - INFO - Загружено 5 пакетов для сессии 16
2025-05-26 13:47:46,703 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 13:47:46,703 - INFO - Завершение работы приложения
2025-05-26 13:47:57,848 - INFO - Подключение к БД установлено
2025-05-26 13:47:57,850 - INFO - Подключение к БД установлено
2025-05-26 13:48:00,568 - INFO - Список сессий обновлен, количество: 16
2025-05-26 13:48:03,100 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 13:48:03,100 - INFO - Завершение работы приложения
2025-05-26 13:56:55,099 - INFO - Подключение к БД установлено
2025-05-26 13:56:55,100 - INFO - Подключение к БД установлено
2025-05-26 13:56:57,840 - INFO - Попытка подключения к серверу
2025-05-26 13:56:57,874 - INFO - Подключение к БД установлено
2025-05-26 13:56:57,874 - INFO - Успешное подключение к серверу
2025-05-26 13:56:59,986 - INFO - Подключение к БД установлено
2025-05-26 13:56:59,986 - INFO - Генерация запущена для сессии 17
2025-05-26 13:57:05,872 - INFO - Подключение к БД установлено
2025-05-26 13:57:05,872 - INFO - Генерация остановлена при завершении работы
2025-05-26 13:57:05,876 - INFO - Подключение к БД установлено
2025-05-26 13:57:05,876 - INFO - Отключено от сервера
2025-05-26 13:57:05,877 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 13:57:05,877 - INFO - Отключено от сервера при завершении работы
2025-05-26 13:57:05,877 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 13:57:05,877 - INFO - Завершение работы приложения
2025-05-26 13:57:21,486 - INFO - Подключение к БД установлено
2025-05-26 13:57:21,487 - INFO - Подключение к БД установлено
2025-05-26 13:57:25,118 - INFO - Список сессий обновлен, количество: 17
2025-05-26 13:57:27,099 - INFO - Попытка подключения к серверу
2025-05-26 13:57:27,133 - INFO - Подключение к БД установлено
2025-05-26 13:57:27,133 - INFO - Успешное подключение к серверу
2025-05-26 13:57:27,662 - INFO - Подключение к БД установлено
2025-05-26 13:57:27,662 - INFO - Генерация запущена для сессии 18
2025-05-26 13:57:33,741 - INFO - Подключение к БД установлено
2025-05-26 13:57:33,741 - INFO - Генерация остановлена при завершении работы
2025-05-26 13:57:33,743 - INFO - Подключение к БД установлено
2025-05-26 13:57:33,744 - INFO - Отключено от сервера
2025-05-26 13:57:33,744 - INFO - Отключено от сервера при завершении работы
2025-05-26 13:57:33,744 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 13:57:33,744 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 13:57:33,745 - INFO - Завершение работы приложения
2025-05-26 18:16:30,864 - INFO - Подключение к БД установлено
2025-05-26 18:16:30,869 - INFO - Подключение к БД установлено
2025-05-26 18:16:38,274 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 18:16:38,274 - INFO - Завершение работы приложения
2025-05-26 18:36:50,267 - INFO - Подключение к БД установлено
2025-05-26 18:36:50,268 - INFO - Подключение к БД установлено
2025-05-26 18:36:53,138 - INFO - Попытка подключения к серверу
2025-05-26 18:36:53,189 - INFO - Подключение к БД установлено
2025-05-26 18:36:53,189 - INFO - Успешное подключение к серверу
2025-05-26 18:37:06,934 - INFO - Подключение к БД установлено
2025-05-26 18:37:06,935 - INFO - Отключено от сервера
2025-05-26 18:37:06,935 - INFO - Отключено от сервера при завершении работы
2025-05-26 18:37:06,935 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 18:37:06,936 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 18:37:06,936 - INFO - Завершение работы приложения
2025-05-26 18:37:26,057 - INFO - Подключение к БД установлено
2025-05-26 18:37:26,058 - INFO - Подключение к БД установлено
2025-05-26 18:37:27,502 - INFO - Попытка подключения к серверу
2025-05-26 18:37:27,540 - INFO - Подключение к БД установлено
2025-05-26 18:37:27,540 - INFO - Успешное подключение к серверу
2025-05-26 18:38:10,726 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 18:38:10,726 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x0000021555428170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 18:38:10,726 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 18:38:10,726 - INFO - Подключение к БД установлено
2025-05-26 18:38:10,726 - INFO - Отключено от сервера
2025-05-26 18:38:10,727 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 18:38:10,727 - INFO - Подключение к БД установлено
2025-05-26 18:38:10,727 - INFO - Отключено от сервера
2025-05-26 18:38:10,727 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 18:38:17,565 - WARNING - Connection closed Connection is already closed.
2025-05-26 18:38:17,565 - INFO - on_reconnect not defined
2025-05-26 18:38:21,647 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=vUQu36l5GZNg1G_QvKE9hA (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002155542A780>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-26 18:50:03,434 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 18:50:03,434 - INFO - Завершение работы приложения
2025-05-26 18:52:33,123 - INFO - Подключение к БД установлено
2025-05-26 18:52:33,124 - INFO - Подключение к БД установлено
2025-05-26 18:52:34,196 - INFO - Попытка подключения к серверу
2025-05-26 18:52:34,247 - INFO - Подключение к БД установлено
2025-05-26 18:52:34,248 - INFO - Успешное подключение к серверу
2025-05-26 18:52:39,107 - INFO - Подключение к БД установлено
2025-05-26 18:52:39,108 - INFO - Отключено от сервера
2025-05-26 18:52:39,108 - INFO - Отключено от сервера при завершении работы
2025-05-26 18:52:39,108 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 18:52:39,108 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 18:52:39,108 - INFO - Завершение работы приложения
2025-05-26 18:53:21,345 - INFO - Подключение к БД установлено
2025-05-26 18:53:21,346 - INFO - Подключение к БД установлено
2025-05-26 18:53:22,370 - INFO - Попытка подключения к серверу
2025-05-26 18:53:22,378 - INFO - Подключение к БД установлено
2025-05-26 18:53:22,379 - INFO - Успешное подключение к серверу
2025-05-26 18:53:25,529 - INFO - Подключение к БД установлено
2025-05-26 18:53:25,529 - INFO - Отключено от сервера при завершении работы
2025-05-26 18:53:25,529 - INFO - Отключено от сервера
2025-05-26 18:53:25,530 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 18:53:25,530 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 18:53:25,530 - INFO - Завершение работы приложения
2025-05-26 19:04:37,994 - INFO - Подключение к БД установлено
2025-05-26 19:04:37,995 - INFO - Подключение к БД установлено
2025-05-26 19:04:38,940 - INFO - Попытка подключения к серверу
2025-05-26 19:04:38,948 - INFO - Подключение к БД установлено
2025-05-26 19:04:38,949 - INFO - Успешное подключение к серверу
2025-05-26 19:04:41,799 - INFO - Подключение к БД установлено
2025-05-26 19:04:41,800 - INFO - Отключено от сервера
2025-05-26 19:04:41,800 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:04:41,800 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:04:41,800 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:04:41,800 - INFO - Завершение работы приложения
2025-05-26 19:31:48,137 - INFO - Подключение к БД установлено
2025-05-26 19:31:48,138 - INFO - Подключение к БД установлено
2025-05-26 19:31:50,945 - ERROR - Ошибка подключения: 404
2025-05-26 19:31:55,445 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:31:55,446 - INFO - Завершение работы приложения
2025-05-26 19:33:46,928 - INFO - Подключение к БД установлено
2025-05-26 19:33:46,929 - INFO - Подключение к БД установлено
2025-05-26 19:33:48,406 - INFO - Попытка подключения к серверу
2025-05-26 19:33:48,429 - INFO - Подключение к БД установлено
2025-05-26 19:33:48,429 - INFO - Успешное подключение к серверу
2025-05-26 19:33:51,755 - INFO - Подключение к БД установлено
2025-05-26 19:33:51,755 - INFO - Отключено от сервера
2025-05-26 19:33:51,755 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:33:51,756 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:33:51,756 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:33:51,756 - INFO - Завершение работы приложения
2025-05-26 19:35:51,636 - INFO - Подключение к БД установлено
2025-05-26 19:35:51,637 - INFO - Подключение к БД установлено
2025-05-26 19:35:52,762 - INFO - Попытка подключения к серверу
2025-05-26 19:35:52,799 - INFO - Подключение к БД установлено
2025-05-26 19:35:52,799 - INFO - Успешное подключение к серверу
2025-05-26 19:35:59,311 - INFO - Подключение к БД установлено
2025-05-26 19:35:59,311 - INFO - Отключено от сервера
2025-05-26 19:35:59,311 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:35:59,312 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:35:59,312 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:35:59,312 - INFO - Завершение работы приложения
2025-05-26 19:36:29,710 - INFO - Подключение к БД установлено
2025-05-26 19:36:29,712 - INFO - Подключение к БД установлено
2025-05-26 19:36:30,565 - INFO - Попытка подключения к серверу
2025-05-26 19:36:30,570 - INFO - Подключение к БД установлено
2025-05-26 19:36:30,570 - INFO - Успешное подключение к серверу
2025-05-26 19:36:32,993 - INFO - Подключение к БД установлено
2025-05-26 19:36:32,993 - INFO - Отключено от сервера
2025-05-26 19:36:32,994 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:36:32,994 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:36:32,994 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:36:32,994 - INFO - Завершение работы приложения
2025-05-26 19:37:32,252 - INFO - Подключение к БД установлено
2025-05-26 19:37:32,254 - INFO - Подключение к БД установлено
2025-05-26 19:37:34,692 - INFO - Попытка подключения к серверу
2025-05-26 19:37:34,731 - INFO - Подключение к БД установлено
2025-05-26 19:37:34,731 - INFO - Успешное подключение к серверу
2025-05-26 19:37:39,869 - INFO - Подключение к БД установлено
2025-05-26 19:37:39,869 - INFO - Отключено от сервера
2025-05-26 19:37:39,870 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:37:39,870 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:37:39,870 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:37:39,870 - INFO - Завершение работы приложения
2025-05-26 19:38:24,996 - INFO - Подключение к БД установлено
2025-05-26 19:38:24,997 - INFO - Подключение к БД установлено
2025-05-26 19:38:25,841 - INFO - Попытка подключения к серверу
2025-05-26 19:38:25,881 - INFO - Подключение к БД установлено
2025-05-26 19:38:25,881 - INFO - Успешное подключение к серверу
2025-05-26 19:38:27,892 - INFO - Подключение к БД установлено
2025-05-26 19:38:27,892 - INFO - Отключено от сервера
2025-05-26 19:38:27,893 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:38:27,893 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:38:27,893 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:38:27,893 - INFO - Завершение работы приложения
2025-05-26 19:39:28,655 - INFO - Подключение к БД установлено
2025-05-26 19:39:28,656 - INFO - Подключение к БД установлено
2025-05-26 19:39:29,581 - INFO - Попытка подключения к серверу
2025-05-26 19:39:29,618 - INFO - Подключение к БД установлено
2025-05-26 19:39:29,618 - INFO - Успешное подключение к серверу
2025-05-26 19:39:45,282 - INFO - Подключение к БД установлено
2025-05-26 19:39:45,282 - INFO - Отключено от сервера
2025-05-26 19:39:45,282 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:39:45,282 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:39:45,283 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:39:45,283 - INFO - Завершение работы приложения
2025-05-26 19:40:47,285 - INFO - Подключение к БД установлено
2025-05-26 19:40:47,287 - INFO - Подключение к БД установлено
2025-05-26 19:40:48,048 - INFO - Попытка подключения к серверу
2025-05-26 19:40:48,081 - INFO - Подключение к БД установлено
2025-05-26 19:40:48,081 - INFO - Успешное подключение к серверу
2025-05-26 19:40:49,279 - INFO - Подключение к БД установлено
2025-05-26 19:40:49,279 - INFO - Генерация запущена для сессии 1
2025-05-26 19:41:43,003 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 19:41:43,004 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000001C498548170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 19:41:43,004 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 19:41:43,004 - INFO - Подключение к БД установлено
2025-05-26 19:41:43,004 - INFO - Отключено от сервера
2025-05-26 19:41:43,005 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:41:43,005 - INFO - Подключение к БД установлено
2025-05-26 19:41:43,005 - INFO - Отключено от сервера
2025-05-26 19:41:43,006 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:41:48,107 - WARNING - Connection closed Connection is already closed.
2025-05-26 19:41:48,107 - INFO - on_reconnect not defined
2025-05-26 19:41:52,189 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=l8AGuTPJJKSLezL8V5c4uw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C49854A780>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-26 19:43:52,208 - INFO - Подключение к БД установлено
2025-05-26 19:43:52,209 - INFO - Подключение к БД установлено
2025-05-26 19:43:53,540 - INFO - Попытка подключения к серверу
2025-05-26 19:43:53,577 - INFO - Подключение к БД установлено
2025-05-26 19:43:53,577 - INFO - Успешное подключение к серверу
2025-05-26 19:43:59,143 - INFO - Подключение к БД установлено
2025-05-26 19:43:59,143 - INFO - Отключено от сервера
2025-05-26 19:43:59,144 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:43:59,144 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:43:59,144 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:43:59,144 - INFO - Завершение работы приложения
2025-05-26 19:46:28,713 - INFO - Подключение к БД установлено
2025-05-26 19:46:28,714 - INFO - Подключение к БД установлено
2025-05-26 19:46:29,943 - INFO - Попытка подключения к серверу
2025-05-26 19:46:29,982 - INFO - Подключение к БД установлено
2025-05-26 19:46:29,982 - INFO - Успешное подключение к серверу
2025-05-26 19:46:31,766 - INFO - Подключение к БД установлено
2025-05-26 19:46:31,767 - INFO - Генерация запущена для сессии 2
2025-05-26 19:47:04,159 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 19:47:04,159 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x0000020E23DE8170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 19:47:04,159 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 19:47:04,159 - INFO - Подключение к БД установлено
2025-05-26 19:47:04,159 - INFO - Отключено от сервера
2025-05-26 19:47:04,159 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:47:04,160 - INFO - Подключение к БД установлено
2025-05-26 19:47:04,160 - INFO - Отключено от сервера
2025-05-26 19:47:04,160 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:47:07,440 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:47:07,440 - INFO - Завершение работы приложения
2025-05-26 19:48:59,847 - INFO - Подключение к БД установлено
2025-05-26 19:48:59,849 - INFO - Подключение к БД установлено
2025-05-26 19:49:00,745 - INFO - Попытка подключения к серверу
2025-05-26 19:49:00,798 - INFO - Подключение к БД установлено
2025-05-26 19:49:00,798 - INFO - Успешное подключение к серверу
2025-05-26 19:49:02,049 - INFO - Подключение к БД установлено
2025-05-26 19:49:02,050 - INFO - Генерация запущена для сессии 3
2025-05-26 19:49:07,324 - INFO - Подключение к БД установлено
2025-05-26 19:49:07,325 - INFO - Генерация остановлена
2025-05-26 19:49:09,243 - INFO - Подключение к БД установлено
2025-05-26 19:49:09,243 - INFO - Генерация запущена для сессии 4
2025-05-26 19:49:12,807 - INFO - Подключение к БД установлено
2025-05-26 19:49:12,807 - INFO - Генерация остановлена
2025-05-26 19:49:13,889 - INFO - Подключение к БД установлено
2025-05-26 19:49:13,889 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:49:13,889 - INFO - Отключено от сервера
2025-05-26 19:49:13,889 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:49:13,890 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:49:13,890 - INFO - Завершение работы приложения
2025-05-26 19:51:26,254 - INFO - Подключение к БД установлено
2025-05-26 19:51:26,255 - INFO - Подключение к БД установлено
2025-05-26 19:51:27,138 - INFO - Попытка подключения к серверу
2025-05-26 19:51:27,176 - INFO - Подключение к БД установлено
2025-05-26 19:51:27,176 - INFO - Успешное подключение к серверу
2025-05-26 19:51:28,104 - INFO - Подключение к БД установлено
2025-05-26 19:51:28,104 - INFO - Генерация запущена для сессии 5
2025-05-26 19:51:32,719 - INFO - Подключение к БД установлено
2025-05-26 19:51:32,719 - INFO - Генерация остановлена
2025-05-26 19:51:39,608 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 19:51:39,609 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x00000205D1418170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 19:51:39,609 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 19:51:39,609 - INFO - Подключение к БД установлено
2025-05-26 19:51:39,609 - INFO - Отключено от сервера
2025-05-26 19:51:39,609 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:51:39,610 - INFO - Подключение к БД установлено
2025-05-26 19:51:39,610 - INFO - Отключено от сервера
2025-05-26 19:51:39,610 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:51:47,187 - WARNING - Connection closed Connection is already closed.
2025-05-26 19:51:47,187 - INFO - on_reconnect not defined
2025-05-26 19:51:51,249 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=muwIahfd8yJM73D0E786YQ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205D141A810>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-26 19:52:57,685 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:52:57,685 - INFO - Завершение работы приложения
2025-05-26 19:52:58,888 - INFO - Подключение к БД установлено
2025-05-26 19:52:58,889 - INFO - Подключение к БД установлено
2025-05-26 19:53:00,499 - INFO - Попытка подключения к серверу
2025-05-26 19:53:00,537 - INFO - Подключение к БД установлено
2025-05-26 19:53:00,537 - INFO - Успешное подключение к серверу
2025-05-26 19:53:01,919 - INFO - Подключение к БД установлено
2025-05-26 19:53:01,919 - INFO - Генерация запущена для сессии 6
2025-05-26 19:53:08,931 - INFO - Подключение к БД установлено
2025-05-26 19:53:08,931 - INFO - Генерация остановлена при завершении работы
2025-05-26 19:53:08,935 - INFO - Подключение к БД установлено
2025-05-26 19:53:08,935 - INFO - Отключено от сервера
2025-05-26 19:53:08,935 - INFO - Отключено от сервера при завершении работы
2025-05-26 19:53:08,935 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 19:53:08,936 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 19:53:08,936 - INFO - Завершение работы приложения
2025-05-26 20:16:28,639 - INFO - Подключение к БД установлено
2025-05-26 20:16:28,641 - INFO - Подключение к БД установлено
2025-05-26 20:16:29,902 - INFO - Попытка подключения к серверу
2025-05-26 20:16:29,939 - INFO - Подключение к БД установлено
2025-05-26 20:16:29,939 - INFO - Успешное подключение к серверу
2025-05-26 20:16:31,412 - INFO - Подключение к БД установлено
2025-05-26 20:16:31,412 - INFO - Генерация запущена для сессии 7
2025-05-26 20:17:09,875 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 20:17:09,875 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x0000022104E38170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 20:17:09,875 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 20:17:09,875 - INFO - Подключение к БД установлено
2025-05-26 20:17:09,875 - INFO - Отключено от сервера
2025-05-26 20:17:09,876 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:17:09,876 - INFO - Подключение к БД установлено
2025-05-26 20:17:09,876 - INFO - Отключено от сервера
2025-05-26 20:17:09,876 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:17:09,978 - WARNING - Connection closed Connection is already closed.
2025-05-26 20:17:09,978 - INFO - on_reconnect not defined
2025-05-26 20:17:10,741 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:17:10,741 - INFO - Завершение работы приложения
2025-05-26 20:18:31,142 - INFO - Подключение к БД установлено
2025-05-26 20:18:31,145 - INFO - Подключение к БД установлено
2025-05-26 20:18:32,276 - INFO - Попытка подключения к серверу
2025-05-26 20:18:32,311 - INFO - Подключение к БД установлено
2025-05-26 20:18:32,311 - INFO - Успешное подключение к серверу
2025-05-26 20:19:01,487 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 20:19:01,487 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000001F25EE18170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 20:19:01,487 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 20:19:01,488 - INFO - Подключение к БД установлено
2025-05-26 20:19:01,488 - INFO - Отключено от сервера
2025-05-26 20:19:01,488 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:19:01,488 - INFO - Подключение к БД установлено
2025-05-26 20:19:01,488 - INFO - Отключено от сервера
2025-05-26 20:19:01,488 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:19:02,342 - WARNING - Connection closed Connection is already closed.
2025-05-26 20:19:02,342 - INFO - on_reconnect not defined
2025-05-26 20:19:06,441 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=9GgrFkf3qGAh3-e8Wf0IOg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F25EE1AB70>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-26 20:22:06,387 - INFO - Попытка подключения к серверу
2025-05-26 20:22:06,424 - INFO - Подключение к БД установлено
2025-05-26 20:22:06,424 - INFO - Успешное подключение к серверу
2025-05-26 20:22:07,351 - INFO - Подключение к БД установлено
2025-05-26 20:22:07,352 - INFO - Генерация запущена для сессии 1
2025-05-26 20:23:22,820 - INFO - Подключение к БД установлено
2025-05-26 20:23:22,820 - INFO - Генерация остановлена при завершении работы
2025-05-26 20:23:22,829 - INFO - Подключение к БД установлено
2025-05-26 20:23:22,829 - INFO - Отключено от сервера
2025-05-26 20:23:22,829 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:23:22,829 - INFO - Отключено от сервера при завершении работы
2025-05-26 20:23:22,830 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:23:22,830 - INFO - Завершение работы приложения
2025-05-26 20:23:24,322 - INFO - Подключение к БД установлено
2025-05-26 20:23:24,325 - INFO - Подключение к БД установлено
2025-05-26 20:23:26,333 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:23:26,333 - INFO - Завершение работы приложения
2025-05-26 20:24:23,080 - INFO - Подключение к БД установлено
2025-05-26 20:24:23,081 - INFO - Подключение к БД установлено
2025-05-26 20:24:24,240 - INFO - Попытка подключения к серверу
2025-05-26 20:24:24,276 - INFO - Подключение к БД установлено
2025-05-26 20:24:24,276 - INFO - Успешное подключение к серверу
2025-05-26 20:24:25,468 - INFO - Подключение к БД установлено
2025-05-26 20:24:25,468 - INFO - Генерация запущена для сессии 2
2025-05-26 20:24:32,238 - INFO - Подключение к БД установлено
2025-05-26 20:24:32,238 - INFO - Генерация остановлена
2025-05-26 20:24:33,238 - INFO - Подключение к БД установлено
2025-05-26 20:24:33,238 - INFO - Отключено от сервера
2025-05-26 20:24:33,238 - INFO - Отключено от сервера при завершении работы
2025-05-26 20:24:33,239 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:24:33,239 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:24:33,239 - INFO - Завершение работы приложения
2025-05-26 20:25:30,693 - INFO - Подключение к БД установлено
2025-05-26 20:25:30,694 - INFO - Подключение к БД установлено
2025-05-26 20:25:32,635 - INFO - Попытка подключения к серверу
2025-05-26 20:25:32,672 - INFO - Подключение к БД установлено
2025-05-26 20:25:32,672 - INFO - Успешное подключение к серверу
2025-05-26 20:25:33,727 - INFO - Подключение к БД установлено
2025-05-26 20:25:33,728 - INFO - Генерация запущена для сессии 3
2025-05-26 20:26:50,863 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 20:26:50,864 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000001CEE2178170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 20:26:50,864 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 20:26:50,864 - INFO - Подключение к БД установлено
2025-05-26 20:26:50,864 - INFO - Отключено от сервера
2025-05-26 20:26:50,864 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:26:50,864 - INFO - Подключение к БД установлено
2025-05-26 20:26:50,865 - INFO - Отключено от сервера
2025-05-26 20:26:50,865 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:26:52,708 - WARNING - Connection closed Connection is already closed.
2025-05-26 20:26:52,708 - INFO - on_reconnect not defined
2025-05-26 20:26:56,812 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=P-kDBTJB2hC3bMhiqchyaA (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CEE217A7E0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-26 20:27:21,583 - INFO - Подключение к БД установлено
2025-05-26 20:27:21,585 - INFO - Подключение к БД установлено
2025-05-26 20:27:22,758 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:27:22,758 - INFO - Завершение работы приложения
2025-05-26 20:27:25,314 - INFO - Подключение к БД установлено
2025-05-26 20:27:25,315 - INFO - Подключение к БД установлено
2025-05-26 20:27:26,318 - INFO - Попытка подключения к серверу
2025-05-26 20:27:26,346 - INFO - Подключение к БД установлено
2025-05-26 20:27:26,347 - INFO - Успешное подключение к серверу
2025-05-26 20:27:27,405 - INFO - Подключение к БД установлено
2025-05-26 20:27:27,405 - INFO - Генерация запущена для сессии 4
2025-05-26 20:27:44,478 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 20:27:44,478 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000001D56C128170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 20:27:44,478 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 20:27:44,479 - INFO - Подключение к БД установлено
2025-05-26 20:27:44,479 - INFO - Отключено от сервера
2025-05-26 20:27:44,479 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:27:44,480 - INFO - Подключение к БД установлено
2025-05-26 20:27:44,480 - INFO - Отключено от сервера
2025-05-26 20:27:44,480 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:27:46,354 - WARNING - Connection closed Connection is already closed.
2025-05-26 20:27:46,354 - INFO - on_reconnect not defined
2025-05-26 20:27:46,847 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:27:46,848 - INFO - Завершение работы приложения
2025-05-26 20:28:20,804 - INFO - Подключение к БД установлено
2025-05-26 20:28:20,805 - INFO - Подключение к БД установлено
2025-05-26 20:28:21,859 - INFO - Попытка подключения к серверу
2025-05-26 20:28:21,896 - INFO - Подключение к БД установлено
2025-05-26 20:28:21,896 - INFO - Успешное подключение к серверу
2025-05-26 20:28:22,919 - INFO - Подключение к БД установлено
2025-05-26 20:28:22,919 - INFO - Генерация запущена для сессии 5
2025-05-26 20:28:36,249 - INFO - Подключение к БД установлено
2025-05-26 20:28:36,250 - INFO - Генерация остановлена
2025-05-26 20:28:38,896 - INFO - Подключение к БД установлено
2025-05-26 20:28:38,897 - INFO - Отключено от сервера
2025-05-26 20:28:38,897 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:28:38,897 - INFO - Отключено от сервера при завершении работы
2025-05-26 20:28:38,898 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:28:38,898 - INFO - Завершение работы приложения
2025-05-26 20:31:21,144 - INFO - Подключение к БД установлено
2025-05-26 20:31:21,145 - INFO - Подключение к БД установлено
2025-05-26 20:31:22,097 - INFO - Попытка подключения к серверу
2025-05-26 20:31:22,140 - INFO - Подключение к БД установлено
2025-05-26 20:31:22,140 - INFO - Успешное подключение к серверу
2025-05-26 20:31:23,101 - INFO - Подключение к БД установлено
2025-05-26 20:31:23,101 - INFO - Генерация запущена для сессии 6
2025-05-26 20:31:30,960 - INFO - Подключение к БД установлено
2025-05-26 20:31:30,960 - INFO - Генерация остановлена
2025-05-26 20:31:32,633 - INFO - Подключение к БД установлено
2025-05-26 20:31:32,633 - INFO - Отключено от сервера
2025-05-26 20:31:32,633 - INFO - Отключено от сервера при завершении работы
2025-05-26 20:31:32,634 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:31:32,634 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:31:32,634 - INFO - Завершение работы приложения
2025-05-26 20:35:32,959 - INFO - Подключение к БД установлено
2025-05-26 20:35:32,961 - INFO - Подключение к БД установлено
2025-05-26 20:35:35,077 - INFO - Попытка подключения к серверу
2025-05-26 20:35:35,118 - INFO - Подключение к БД установлено
2025-05-26 20:35:35,118 - INFO - Успешное подключение к серверу
2025-05-26 20:35:36,574 - INFO - Подключение к БД установлено
2025-05-26 20:35:36,574 - INFO - Генерация запущена для сессии 7
2025-05-26 20:36:04,923 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 20:36:04,923 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000001DFABE08170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 20:36:04,923 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 20:36:04,924 - INFO - Подключение к БД установлено
2025-05-26 20:36:04,924 - INFO - Отключено от сервера
2025-05-26 20:36:04,924 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:36:04,924 - INFO - Подключение к БД установлено
2025-05-26 20:36:04,924 - INFO - Отключено от сервера
2025-05-26 20:36:04,924 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:36:05,151 - WARNING - Connection closed Connection is already closed.
2025-05-26 20:36:05,152 - INFO - on_reconnect not defined
2025-05-26 20:36:06,140 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:36:06,141 - INFO - Завершение работы приложения
2025-05-26 20:41:36,560 - INFO - Подключение к БД установлено
2025-05-26 20:41:36,562 - INFO - Подключение к БД установлено
2025-05-26 20:41:37,436 - INFO - Попытка подключения к серверу
2025-05-26 20:41:37,474 - INFO - Подключение к БД установлено
2025-05-26 20:41:37,474 - INFO - Успешное подключение к серверу
2025-05-26 20:41:38,720 - INFO - Подключение к БД установлено
2025-05-26 20:41:38,720 - INFO - Генерация запущена для сессии 8
2025-05-26 20:41:55,728 - INFO - Подключение к БД установлено
2025-05-26 20:41:55,728 - INFO - Генерация остановлена
2025-05-26 20:42:00,954 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 20:42:00,954 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x00000148EB808170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 20:42:00,954 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 20:42:00,954 - INFO - Подключение к БД установлено
2025-05-26 20:42:00,954 - INFO - Отключено от сервера
2025-05-26 20:42:00,955 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:42:00,955 - INFO - Подключение к БД установлено
2025-05-26 20:42:00,955 - INFO - Отключено от сервера
2025-05-26 20:42:00,955 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:42:05,077 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:42:05,077 - INFO - Завершение работы приложения
2025-05-26 20:52:10,119 - INFO - Подключение к БД установлено
2025-05-26 20:52:10,121 - INFO - Подключение к БД установлено
2025-05-26 20:52:11,075 - INFO - Попытка подключения к серверу
2025-05-26 20:52:11,114 - INFO - Подключение к БД установлено
2025-05-26 20:52:11,114 - INFO - Успешное подключение к серверу
2025-05-26 20:52:35,096 - INFO - Список сессий обновлен, количество: 8
2025-05-26 20:52:36,073 - INFO - Для сессии 8 не найдено пакетов
2025-05-26 20:52:36,073 - WARNING - Предупреждение: Для выбранной сессии нет пакетов данных
2025-05-26 20:52:36,651 - INFO - Для сессии 7 не найдено пакетов
2025-05-26 20:52:36,651 - WARNING - Предупреждение: Для выбранной сессии нет пакетов данных
2025-05-26 20:52:38,721 - INFO - Подключение к БД установлено
2025-05-26 20:52:38,722 - INFO - Отключено от сервера
2025-05-26 20:52:38,722 - INFO - Отключено от сервера при завершении работы
2025-05-26 20:52:38,722 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:52:38,722 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 20:52:38,723 - INFO - Завершение работы приложения
2025-05-26 20:54:21,309 - INFO - Подключение к БД установлено
2025-05-26 20:54:21,311 - INFO - Подключение к БД установлено
2025-05-26 20:54:22,508 - INFO - Попытка подключения к серверу
2025-05-26 20:54:22,553 - INFO - Подключение к БД установлено
2025-05-26 20:54:22,553 - INFO - Успешное подключение к серверу
2025-05-26 20:54:29,155 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-26 20:54:29,155 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x0000026486338170> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-26 20:54:29,155 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-26 20:54:29,155 - INFO - Подключение к БД установлено
2025-05-26 20:54:29,155 - INFO - Отключено от сервера
2025-05-26 20:54:29,155 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:54:29,156 - INFO - Подключение к БД установлено
2025-05-26 20:54:29,156 - INFO - Отключено от сервера
2025-05-26 20:54:29,156 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 20:54:32,559 - WARNING - Connection closed Connection is already closed.
2025-05-26 20:54:32,559 - INFO - on_reconnect not defined
2025-05-26 20:54:36,633 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=O6FGDOQUCr_zhdxAg0vRBw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002648633A8A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-26 21:01:49,852 - INFO - Подключение к БД установлено
2025-05-26 21:01:49,854 - INFO - Подключение к БД установлено
2025-05-26 21:01:51,089 - INFO - Попытка подключения к серверу
2025-05-26 21:01:51,128 - INFO - Подключение к БД установлено
2025-05-26 21:01:51,128 - INFO - Успешное подключение к серверу
2025-05-26 21:01:53,032 - INFO - Подключение к БД установлено
2025-05-26 21:01:53,032 - INFO - Генерация запущена для сессии 9
2025-05-26 21:02:13,816 - INFO - Подключение к БД установлено
2025-05-26 21:02:13,816 - INFO - Генерация остановлена
2025-05-26 21:02:17,569 - INFO - Список сессий обновлен, количество: 9
2025-05-26 21:02:18,928 - INFO - Загружено 10 пакетов для сессии 9
2025-05-26 21:02:21,088 - INFO - Подключение к БД установлено
2025-05-26 21:02:21,088 - INFO - Отключено от сервера при завершении работы
2025-05-26 21:02:21,088 - INFO - Отключено от сервера
2025-05-26 21:02:21,088 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 21:02:21,089 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 21:02:21,089 - INFO - Завершение работы приложения
2025-05-26 21:30:25,948 - INFO - Подключение к БД установлено
2025-05-26 21:30:25,949 - INFO - Подключение к БД установлено
2025-05-26 21:30:28,764 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 21:30:28,764 - INFO - Завершение работы приложения
2025-05-26 22:41:45,377 - INFO - Подключение к БД установлено
2025-05-26 22:41:45,379 - INFO - Подключение к БД установлено
2025-05-26 22:41:46,635 - INFO - Попытка подключения к серверу
2025-05-26 22:41:46,680 - INFO - Подключение к БД установлено
2025-05-26 22:41:46,680 - INFO - Успешное подключение к серверу
2025-05-26 22:41:47,373 - INFO - Подключение к БД установлено
2025-05-26 22:41:47,373 - INFO - Генерация запущена для сессии 1
2025-05-26 22:42:00,967 - INFO - Подключение к БД установлено
2025-05-26 22:42:00,967 - INFO - Генерация остановлена
2025-05-26 22:42:03,047 - INFO - Список сессий обновлен, количество: 1
2025-05-26 22:42:03,599 - INFO - Загружено 7 пакетов для сессии 1
2025-05-26 22:42:05,754 - INFO - Подключение к БД установлено
2025-05-26 22:42:05,754 - INFO - Отключено от сервера
2025-05-26 22:42:05,754 - INFO - Отключено от сервера при завершении работы
2025-05-26 22:42:05,754 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-26 22:42:05,755 - INFO - Подключение к БД закрыто при завершении работы
2025-05-26 22:42:05,755 - INFO - Завершение работы приложения
2025-05-26 23:49:45,482 - INFO - Подключение к БД установлено
2025-05-26 23:49:45,483 - INFO - Подключение к БД установлено
2025-05-26 23:49:50,788 - ERROR - Ошибка подключения: HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B9E56D550>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-27 10:25:23,046 - INFO - Подключение к БД закрыто при завершении работы
2025-05-27 10:25:23,050 - INFO - Завершение работы приложения
2025-05-27 10:46:54,266 - INFO - Подключение к БД установлено
2025-05-27 10:46:54,267 - INFO - Подключение к БД установлено
2025-05-27 10:46:56,691 - INFO - Попытка подключения к серверу
2025-05-27 10:46:56,738 - INFO - Подключение к БД установлено
2025-05-27 10:46:56,738 - INFO - Успешное подключение к серверу
2025-05-27 10:46:58,009 - INFO - Подключение к БД установлено
2025-05-27 10:46:58,009 - INFO - Генерация запущена для сессии 1
2025-05-27 10:47:12,550 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-27 10:47:12,550 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000002BA93ABC230> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-27 10:47:12,550 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-27 10:47:12,551 - INFO - Подключение к БД установлено
2025-05-27 10:47:12,551 - INFO - Отключено от сервера
2025-05-27 10:47:12,551 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 10:47:12,552 - INFO - Подключение к БД установлено
2025-05-27 10:47:12,552 - INFO - Отключено от сервера
2025-05-27 10:47:12,552 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 10:47:16,749 - WARNING - Connection closed Connection is already closed.
2025-05-27 10:47:16,749 - INFO - on_reconnect not defined
2025-05-27 10:47:20,851 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=yAr3jhSY3DYwEzb3gNbrgA (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BA93ABE870>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-27 15:11:50,337 - INFO - Подключение к БД установлено
2025-05-27 15:11:50,338 - INFO - Подключение к БД установлено
2025-05-27 15:11:57,416 - INFO - Попытка подключения к серверу
2025-05-27 15:11:57,450 - INFO - Подключение к БД установлено
2025-05-27 15:11:57,450 - INFO - Успешное подключение к серверу
2025-05-27 15:11:59,964 - INFO - Подключение к БД установлено
2025-05-27 15:11:59,964 - INFO - Генерация запущена для сессии 2
2025-05-27 15:12:25,474 - INFO - Подключение к БД установлено
2025-05-27 15:12:25,475 - INFO - Генерация остановлена
2025-05-27 15:13:24,354 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-27 15:13:24,355 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000001EED1D88230> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-27 15:13:24,355 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-27 15:13:24,355 - INFO - Подключение к БД установлено
2025-05-27 15:13:24,355 - INFO - Отключено от сервера
2025-05-27 15:13:24,355 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 15:13:24,355 - INFO - Подключение к БД установлено
2025-05-27 15:13:24,356 - INFO - Отключено от сервера
2025-05-27 15:13:24,356 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 15:13:27,486 - WARNING - Connection closed Connection is already closed.
2025-05-27 15:13:27,486 - INFO - on_reconnect not defined
2025-05-27 15:13:31,575 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=WGzpE_nRSiaNn_Wg_UacUQ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EED1D8ACC0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-27 15:15:13,112 - INFO - Подключение к БД установлено
2025-05-27 15:15:13,113 - INFO - Подключение к БД установлено
2025-05-27 15:15:13,147 - INFO - Подключение к БД установлено
2025-05-27 15:15:13,148 - INFO - Подключение к БД установлено
2025-05-27 15:15:14,746 - INFO - Попытка подключения к серверу
2025-05-27 15:15:14,781 - INFO - Подключение к БД установлено
2025-05-27 15:15:14,782 - INFO - Успешное подключение к серверу
2025-05-27 15:15:41,924 - INFO - Подключение к БД установлено
2025-05-27 15:15:41,930 - INFO - Подключение к БД установлено
2025-05-27 15:15:46,974 - INFO - Попытка подключения к серверу
2025-05-27 15:15:46,980 - INFO - Подключение к БД установлено
2025-05-27 15:15:46,980 - INFO - Успешное подключение к серверу
2025-05-27 15:15:54,278 - INFO - Подключение к БД установлено
2025-05-27 15:15:54,279 - INFO - Отключено от сервера
2025-05-27 15:15:54,279 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 15:15:54,279 - INFO - Отключено от сервера при завершении работы
2025-05-27 15:15:54,279 - INFO - Подключение к БД закрыто при завершении работы
2025-05-27 15:15:54,280 - INFO - Завершение работы приложения
2025-05-27 15:18:49,910 - INFO - Подключение к БД установлено
2025-05-27 15:18:49,911 - INFO - Подключение к БД установлено
2025-05-27 15:18:51,082 - INFO - Попытка подключения к серверу
2025-05-27 15:18:51,126 - INFO - Подключение к БД установлено
2025-05-27 15:18:51,126 - INFO - Успешное подключение к серверу
2025-05-27 15:18:59,587 - INFO - Подключение к БД установлено
2025-05-27 15:18:59,587 - INFO - Отключено от сервера
2025-05-27 15:18:59,588 - INFO - Отключено от сервера при завершении работы
2025-05-27 15:18:59,588 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 15:18:59,588 - INFO - Подключение к БД закрыто при завершении работы
2025-05-27 15:18:59,588 - INFO - Завершение работы приложения
2025-05-27 15:39:48,770 - INFO - Подключение к БД установлено
2025-05-27 15:39:48,771 - INFO - Подключение к БД установлено
2025-05-27 15:39:50,418 - INFO - Попытка подключения к серверу
2025-05-27 15:39:50,452 - INFO - Подключение к БД установлено
2025-05-27 15:39:50,452 - INFO - Успешное подключение к серверу
2025-05-27 15:39:51,726 - INFO - Подключение к БД установлено
2025-05-27 15:39:51,726 - INFO - Генерация запущена для сессии 1
2025-05-27 15:40:00,661 - INFO - Подключение к БД установлено
2025-05-27 15:40:00,661 - INFO - Генерация остановлена
2025-05-27 15:40:02,533 - INFO - Список сессий обновлен, количество: 1
2025-05-27 15:40:02,966 - INFO - Загружено 4 пакетов для сессии 1
2025-05-27 15:40:04,150 - INFO - Подключение к БД установлено
2025-05-27 15:40:04,150 - INFO - Отключено от сервера
2025-05-27 15:40:04,150 - INFO - Отключено от сервера при завершении работы
2025-05-27 15:40:04,150 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 15:40:04,151 - INFO - Подключение к БД закрыто при завершении работы
2025-05-27 15:40:04,151 - INFO - Завершение работы приложения
2025-05-27 15:40:14,435 - INFO - Подключение к БД установлено
2025-05-27 15:40:14,436 - INFO - Подключение к БД установлено
2025-05-27 15:40:16,502 - INFO - Попытка подключения к серверу
2025-05-27 15:40:16,538 - INFO - Подключение к БД установлено
2025-05-27 15:40:16,538 - INFO - Успешное подключение к серверу
2025-05-27 15:40:17,075 - INFO - Подключение к БД установлено
2025-05-27 15:40:17,075 - INFO - Генерация запущена для сессии 2
2025-05-27 15:40:23,897 - INFO - Подключение к БД установлено
2025-05-27 15:40:23,897 - INFO - Генерация остановлена
2025-05-27 15:40:24,562 - INFO - Подключение к БД установлено
2025-05-27 15:40:24,563 - INFO - Отключено от сервера
2025-05-27 15:40:24,563 - INFO - Отключено от сервера при завершении работы
2025-05-27 15:40:24,563 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 15:40:24,563 - INFO - Подключение к БД закрыто при завершении работы
2025-05-27 15:40:24,563 - INFO - Завершение работы приложения
2025-05-27 17:55:05,508 - INFO - Подключение к БД установлено
2025-05-27 17:55:05,509 - INFO - Подключение к БД установлено
2025-05-27 17:55:08,200 - INFO - Попытка подключения к серверу
2025-05-27 17:55:08,235 - INFO - Подключение к БД установлено
2025-05-27 17:55:08,235 - INFO - Успешное подключение к серверу
2025-05-27 17:55:10,046 - INFO - Подключение к БД установлено
2025-05-27 17:55:10,047 - INFO - Генерация запущена для сессии 3
2025-05-27 17:55:16,873 - INFO - Подключение к БД установлено
2025-05-27 17:55:16,873 - INFO - Генерация остановлена
2025-05-27 18:24:56,284 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-05-27 18:24:56,285 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x00000104F0118230> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-05-27 18:24:56,285 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-05-27 18:24:56,285 - INFO - Подключение к БД установлено
2025-05-27 18:24:56,285 - INFO - Отключено от сервера
2025-05-27 18:24:56,286 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 18:24:56,286 - INFO - Подключение к БД установлено
2025-05-27 18:24:56,286 - INFO - Отключено от сервера
2025-05-27 18:24:56,286 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 18:24:59,182 - WARNING - Connection closed Connection is already closed.
2025-05-27 18:24:59,182 - INFO - on_reconnect not defined
2025-05-27 18:25:03,273 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=QN4-PF8kvExCvxLT6yG74A (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000104F011ACC0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-05-27 19:23:11,140 - INFO - Подключение к БД закрыто при завершении работы
2025-05-27 19:23:11,141 - INFO - Завершение работы приложения
2025-05-27 20:23:47,219 - INFO - Подключение к БД установлено
2025-05-27 20:23:47,220 - INFO - Подключение к БД установлено
2025-05-27 20:23:48,318 - INFO - Попытка подключения к серверу
2025-05-27 20:23:48,351 - INFO - Подключение к БД установлено
2025-05-27 20:23:48,351 - INFO - Успешное подключение к серверу
2025-05-27 20:23:52,207 - INFO - Подключение к БД установлено
2025-05-27 20:23:52,207 - INFO - Генерация запущена для сессии 4
2025-05-27 20:24:06,853 - INFO - Подключение к БД установлено
2025-05-27 20:24:06,853 - INFO - Генерация остановлена
2025-05-27 20:24:08,302 - INFO - Список сессий обновлен, количество: 4
2025-05-27 20:24:08,871 - INFO - Загружено 7 пакетов для сессии 4
2025-05-27 20:24:16,437 - INFO - Подключение к БД установлено
2025-05-27 20:24:16,437 - INFO - Отключено от сервера
2025-05-27 20:24:16,437 - INFO - Отключено от сервера
2025-05-27 20:24:16,437 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-05-27 20:24:16,963 - INFO - Подключение к БД закрыто при завершении работы
2025-05-27 20:24:16,963 - INFO - Завершение работы приложения
2025-05-28 22:46:11,419 - INFO - Подключение к БД установлено
2025-05-28 22:46:11,422 - INFO - Подключение к БД установлено
2025-05-28 22:46:16,738 - INFO - Подключение к БД закрыто при завершении работы
2025-05-28 22:46:16,738 - INFO - Завершение работы приложения
2025-06-04 18:35:38,609 - INFO - Подключение к БД установлено
2025-06-04 18:35:38,610 - INFO - Подключение к БД установлено
2025-06-04 18:35:46,780 - ERROR - Ошибка подключения: HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DDD8B322D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-06-04 18:36:07,027 - ERROR - Ошибка подключения: HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DDD8B32AE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-06-04 18:36:57,324 - INFO - Попытка подключения к серверу
2025-06-04 18:36:57,401 - INFO - Подключение к БД установлено
2025-06-04 18:36:57,401 - INFO - Успешное подключение к серверу
2025-06-04 18:36:59,568 - INFO - Подключение к БД установлено
2025-06-04 18:36:59,568 - INFO - Отключено от сервера
2025-06-04 18:36:59,568 - INFO - Отключено от сервера
2025-06-04 18:36:59,659 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-06-04 18:37:04,937 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 18:37:04,937 - INFO - Завершение работы приложения
2025-06-04 18:38:27,729 - INFO - Подключение к БД установлено
2025-06-04 18:38:27,730 - INFO - Подключение к БД установлено
2025-06-04 18:38:36,530 - ERROR - Ошибка подключения: HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221949622D0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-06-04 18:38:59,075 - INFO - Попытка подключения к серверу
2025-06-04 18:38:59,113 - INFO - Подключение к БД установлено
2025-06-04 18:38:59,113 - INFO - Успешное подключение к серверу
2025-06-04 18:39:01,101 - INFO - Подключение к БД установлено
2025-06-04 18:39:01,101 - INFO - Отключено от сервера
2025-06-04 18:39:01,101 - INFO - Отключено от сервера
2025-06-04 18:39:01,101 - WARNING - Предупреждение: Соединение с сервером закрыто
2025-06-04 18:45:21,511 - INFO - Подключение к БД установлено
2025-06-04 18:45:21,511 - INFO - Подключение к БД установлено
2025-06-04 18:45:27,372 - INFO - Попытка подключения к серверу
2025-06-04 18:45:27,386 - INFO - Подключение к БД установлено
2025-06-04 18:45:27,386 - INFO - Успешное подключение к серверу
2025-06-04 18:45:29,779 - INFO - Подключение к БД установлено
2025-06-04 18:45:29,779 - INFO - Штатное отключение от сервера
2025-06-04 18:45:29,780 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:45:45,763 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 18:45:45,763 - INFO - Завершение работы приложения
2025-06-04 18:46:11,912 - INFO - Подключение к БД установлено
2025-06-04 18:46:11,912 - INFO - Подключение к БД установлено
2025-06-04 18:46:12,961 - INFO - Попытка подключения к серверу
2025-06-04 18:46:12,968 - INFO - Подключение к БД установлено
2025-06-04 18:46:12,968 - INFO - Успешное подключение к серверу
2025-06-04 18:46:13,692 - INFO - Подключение к БД установлено
2025-06-04 18:46:13,693 - INFO - Штатное отключение от сервера
2025-06-04 18:46:13,693 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:46:32,376 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 18:46:32,376 - INFO - Завершение работы приложения
2025-06-04 18:51:02,747 - INFO - Подключение к БД установлено
2025-06-04 18:51:02,748 - INFO - Подключение к БД установлено
2025-06-04 18:51:04,489 - INFO - Попытка подключения к серверу
2025-06-04 18:51:04,497 - INFO - Подключение к БД установлено
2025-06-04 18:51:04,497 - INFO - Успешное подключение к серверу
2025-06-04 18:51:05,573 - INFO - Штатное отключение от сервера
2025-06-04 18:51:05,574 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:51:14,200 - INFO - Попытка подключения к серверу
2025-06-04 18:51:14,203 - INFO - Подключение к БД установлено
2025-06-04 18:51:14,204 - INFO - Успешное подключение к серверу
2025-06-04 18:51:16,023 - INFO - Штатное отключение от сервера
2025-06-04 18:51:16,023 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:51:16,346 - INFO - Попытка подключения к серверу
2025-06-04 18:51:16,349 - INFO - Подключение к БД установлено
2025-06-04 18:51:16,350 - INFO - Успешное подключение к серверу
2025-06-04 18:51:16,506 - INFO - Штатное отключение от сервера
2025-06-04 18:51:16,507 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:51:16,671 - INFO - Попытка подключения к серверу
2025-06-04 18:51:16,674 - INFO - Подключение к БД установлено
2025-06-04 18:51:16,674 - INFO - Успешное подключение к серверу
2025-06-04 18:51:16,825 - INFO - Штатное отключение от сервера
2025-06-04 18:51:16,825 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:51:16,976 - INFO - Попытка подключения к серверу
2025-06-04 18:51:16,979 - INFO - Подключение к БД установлено
2025-06-04 18:51:16,980 - INFO - Успешное подключение к серверу
2025-06-04 18:51:17,181 - INFO - Штатное отключение от сервера
2025-06-04 18:51:17,181 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:51:17,876 - INFO - Попытка подключения к серверу
2025-06-04 18:51:17,879 - INFO - Подключение к БД установлено
2025-06-04 18:51:17,879 - INFO - Успешное подключение к серверу
2025-06-04 18:51:20,771 - INFO - Штатное отключение от сервера
2025-06-04 18:51:20,771 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:51:21,566 - INFO - Попытка подключения к серверу
2025-06-04 18:51:21,570 - INFO - Подключение к БД установлено
2025-06-04 18:51:21,570 - INFO - Успешное подключение к серверу
2025-06-04 18:51:23,990 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 18:51:23,991 - WARNING - Сервер разорвал соединение
2025-06-04 18:51:23,991 - INFO - Отключено от сервера при завершении работы
2025-06-04 18:51:23,991 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 18:51:23,991 - INFO - Завершение работы приложения
2025-06-04 18:51:41,298 - INFO - Подключение к БД установлено
2025-06-04 18:51:41,299 - INFO - Подключение к БД установлено
2025-06-04 18:51:42,270 - INFO - Попытка подключения к серверу
2025-06-04 18:51:42,273 - INFO - Подключение к БД установлено
2025-06-04 18:51:42,273 - INFO - Успешное подключение к серверу
2025-06-04 18:51:44,925 - INFO - Подключение к БД установлено
2025-06-04 18:51:44,925 - INFO - Штатное отключение от сервера
2025-06-04 18:51:44,926 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:51:48,868 - INFO - Попытка подключения к серверу
2025-06-04 18:51:48,871 - INFO - Подключение к БД установлено
2025-06-04 18:51:48,871 - INFO - Успешное подключение к серверу
2025-06-04 18:51:53,233 - INFO - Подключение к БД установлено
2025-06-04 18:51:53,233 - INFO - Штатное отключение от сервера
2025-06-04 18:51:53,234 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:52:03,833 - INFO - Попытка подключения к серверу
2025-06-04 18:52:03,836 - INFO - Подключение к БД установлено
2025-06-04 18:52:03,837 - INFO - Успешное подключение к серверу
2025-06-04 18:52:04,730 - INFO - Подключение к БД установлено
2025-06-04 18:52:04,730 - INFO - Штатное отключение от сервера
2025-06-04 18:52:04,731 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:52:06,126 - INFO - Попытка подключения к серверу
2025-06-04 18:52:06,130 - INFO - Подключение к БД установлено
2025-06-04 18:52:06,130 - INFO - Успешное подключение к серверу
2025-06-04 18:52:08,817 - INFO - Подключение к БД установлено
2025-06-04 18:52:08,817 - INFO - Генерация запущена для сессии 5
2025-06-04 18:52:17,472 - INFO - Подключение к БД установлено
2025-06-04 18:52:17,473 - INFO - Генерация остановлена
2025-06-04 18:52:48,089 - INFO - Подключение к БД установлено
2025-06-04 18:52:48,090 - INFO - Подключение к БД установлено
2025-06-04 18:52:49,468 - INFO - Попытка подключения к серверу
2025-06-04 18:52:49,471 - INFO - Подключение к БД установлено
2025-06-04 18:52:49,472 - INFO - Успешное подключение к серверу
2025-06-04 18:52:50,658 - INFO - Подключение к БД установлено
2025-06-04 18:52:50,658 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:52:50,658 - INFO - Штатное отключение от сервера
2025-06-04 18:53:05,537 - INFO - Попытка подключения к серверу
2025-06-04 18:53:05,541 - INFO - Подключение к БД установлено
2025-06-04 18:53:05,541 - INFO - Успешное подключение к серверу
2025-06-04 18:53:08,950 - INFO - Подключение к БД установлено
2025-06-04 18:53:08,951 - INFO - Штатное отключение от сервера
2025-06-04 18:53:08,951 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:53:09,325 - INFO - Попытка подключения к серверу
2025-06-04 18:53:09,328 - INFO - Подключение к БД установлено
2025-06-04 18:53:09,328 - INFO - Успешное подключение к серверу
2025-06-04 18:53:09,701 - INFO - Подключение к БД установлено
2025-06-04 18:53:09,701 - INFO - Штатное отключение от сервера
2025-06-04 18:53:09,701 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:53:09,870 - INFO - Попытка подключения к серверу
2025-06-04 18:53:09,873 - INFO - Подключение к БД установлено
2025-06-04 18:53:09,873 - INFO - Успешное подключение к серверу
2025-06-04 18:53:10,005 - INFO - Подключение к БД установлено
2025-06-04 18:53:10,005 - INFO - Штатное отключение от сервера
2025-06-04 18:53:10,005 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:53:10,625 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 18:53:10,625 - INFO - Завершение работы приложения
2025-06-04 18:55:47,701 - INFO - Подключение к БД установлено
2025-06-04 18:55:47,701 - INFO - Подключение к БД установлено
2025-06-04 18:55:49,135 - INFO - Попытка подключения к серверу
2025-06-04 18:55:49,146 - INFO - Подключение к БД установлено
2025-06-04 18:55:49,146 - INFO - Успешное подключение к серверу
2025-06-04 18:55:50,459 - INFO - Подключение к БД установлено
2025-06-04 18:55:50,460 - INFO - Штатное отключение от сервера
2025-06-04 18:55:50,460 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 18:55:50,460 - INFO - DEBUG: Текущее сообщение: Соединение с сервером закрыто пользователем
2025-06-04 19:13:06,910 - INFO - Подключение к БД установлено
2025-06-04 19:13:06,910 - INFO - Подключение к БД установлено
2025-06-04 19:13:09,478 - INFO - Попытка подключения к серверу
2025-06-04 19:13:09,485 - INFO - Подключение к БД установлено
2025-06-04 19:13:09,485 - INFO - Успешное подключение к серверу
2025-06-04 19:13:11,036 - INFO - Штатное отключение от сервера
2025-06-04 19:13:11,037 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:13:22,073 - INFO - Попытка подключения к серверу
2025-06-04 19:13:22,076 - INFO - Подключение к БД установлено
2025-06-04 19:13:22,076 - INFO - Успешное подключение к серверу
2025-06-04 19:13:26,542 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 19:13:26,542 - WARNING - Сервер разорвал соединение
2025-06-04 19:13:26,542 - INFO - Отключено от сервера при завершении работы
2025-06-04 19:13:26,543 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:13:26,543 - INFO - Завершение работы приложения
2025-06-04 19:14:47,070 - INFO - Подключение к БД установлено
2025-06-04 19:14:47,071 - INFO - Подключение к БД установлено
2025-06-04 19:14:48,983 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:14:48,983 - INFO - Завершение работы приложения
2025-06-04 19:14:52,160 - INFO - Подключение к БД установлено
2025-06-04 19:14:52,160 - INFO - Подключение к БД установлено
2025-06-04 19:14:56,119 - INFO - Попытка подключения к серверу
2025-06-04 19:14:56,128 - INFO - Подключение к БД установлено
2025-06-04 19:14:56,128 - INFO - Успешное подключение к серверу
2025-06-04 19:14:57,095 - INFO - Штатное отключение от сервера
2025-06-04 19:14:57,095 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:15:34,759 - INFO - Подключение к БД установлено
2025-06-04 19:15:34,760 - INFO - Подключение к БД установлено
2025-06-04 19:15:35,706 - INFO - Попытка подключения к серверу
2025-06-04 19:15:35,710 - INFO - Подключение к БД установлено
2025-06-04 19:15:35,710 - INFO - Успешное подключение к серверу
2025-06-04 19:15:38,580 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-06-04 19:15:38,580 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x0000022EE2121010> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-06-04 19:15:38,580 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-06-04 19:15:38,583 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 19:15:38,583 - WARNING - Сервер разорвал соединение
2025-06-04 19:15:38,583 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 19:15:38,584 - WARNING - Сервер разорвал соединение
2025-06-04 19:15:45,714 - WARNING - Connection closed Connection is already closed.
2025-06-04 19:15:45,714 - INFO - on_reconnect not defined
2025-06-04 19:15:48,397 - INFO - Подключение к БД установлено
2025-06-04 19:15:48,398 - INFO - Успешное подключение к серверу
2025-06-04 19:16:46,030 - INFO - Подключение к БД установлено
2025-06-04 19:16:46,030 - INFO - Подключение к БД установлено
2025-06-04 19:16:47,391 - INFO - Попытка подключения к серверу
2025-06-04 19:16:47,396 - INFO - Подключение к БД установлено
2025-06-04 19:16:47,396 - INFO - Успешное подключение к серверу
2025-06-04 19:16:48,756 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:17:01,554 - INFO - Попытка подключения к серверу
2025-06-04 19:17:01,557 - INFO - Подключение к БД установлено
2025-06-04 19:17:01,558 - INFO - Успешное подключение к серверу
2025-06-04 19:17:03,719 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:17:06,836 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:17:06,836 - INFO - Завершение работы приложения
2025-06-04 19:17:48,274 - INFO - Подключение к БД установлено
2025-06-04 19:17:48,275 - INFO - Подключение к БД установлено
2025-06-04 19:17:49,135 - INFO - Попытка подключения к серверу
2025-06-04 19:17:49,143 - INFO - Подключение к БД установлено
2025-06-04 19:17:49,143 - INFO - Успешное подключение к серверу
2025-06-04 19:17:52,017 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:18:00,393 - INFO - Попытка подключения к серверу
2025-06-04 19:18:00,397 - INFO - Подключение к БД установлено
2025-06-04 19:18:00,397 - INFO - Успешное подключение к серверу
2025-06-04 19:18:01,836 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 19:18:01,836 - INFO - Подключение к БД установлено
2025-06-04 19:18:01,837 - WARNING - Сервер разорвал соединение
2025-06-04 19:18:01,837 - INFO - Отключено от сервера при завершении работы
2025-06-04 19:18:01,837 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:18:01,837 - INFO - Завершение работы приложения
2025-06-04 19:18:24,039 - INFO - Подключение к БД установлено
2025-06-04 19:18:24,039 - INFO - Подключение к БД установлено
2025-06-04 19:18:25,054 - INFO - Попытка подключения к серверу
2025-06-04 19:18:25,061 - INFO - Подключение к БД установлено
2025-06-04 19:18:25,061 - INFO - Успешное подключение к серверу
2025-06-04 19:18:26,513 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:18:37,575 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:18:37,575 - INFO - Завершение работы приложения
2025-06-04 19:18:58,817 - INFO - Подключение к БД установлено
2025-06-04 19:18:58,817 - INFO - Подключение к БД установлено
2025-06-04 19:18:59,546 - INFO - Попытка подключения к серверу
2025-06-04 19:18:59,553 - INFO - Подключение к БД установлено
2025-06-04 19:18:59,554 - INFO - Успешное подключение к серверу
2025-06-04 19:18:59,935 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:19:16,157 - INFO - Попытка подключения к серверу
2025-06-04 19:19:16,160 - INFO - Подключение к БД установлено
2025-06-04 19:19:16,160 - INFO - Успешное подключение к серверу
2025-06-04 19:19:26,168 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:19:29,201 - INFO - Попытка подключения к серверу
2025-06-04 19:19:29,205 - INFO - Подключение к БД установлено
2025-06-04 19:19:29,205 - INFO - Успешное подключение к серверу
2025-06-04 19:19:29,614 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:19:29,800 - INFO - Попытка подключения к серверу
2025-06-04 19:19:29,803 - INFO - Подключение к БД установлено
2025-06-04 19:19:29,803 - INFO - Успешное подключение к серверу
2025-06-04 19:19:29,942 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:19:30,666 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:19:30,666 - INFO - Завершение работы приложения
2025-06-04 19:20:22,935 - INFO - Подключение к БД установлено
2025-06-04 19:20:22,936 - INFO - Подключение к БД установлено
2025-06-04 19:20:23,722 - INFO - Попытка подключения к серверу
2025-06-04 19:20:23,729 - INFO - Подключение к БД установлено
2025-06-04 19:20:23,730 - INFO - Успешное подключение к серверу
2025-06-04 19:20:24,270 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:20:24,814 - INFO - Попытка подключения к серверу
2025-06-04 19:20:24,817 - INFO - Подключение к БД установлено
2025-06-04 19:20:24,817 - INFO - Успешное подключение к серверу
2025-06-04 19:20:24,967 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:20:25,131 - INFO - Попытка подключения к серверу
2025-06-04 19:20:25,134 - INFO - Подключение к БД установлено
2025-06-04 19:20:25,134 - INFO - Успешное подключение к серверу
2025-06-04 19:20:25,278 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:20:25,430 - INFO - Попытка подключения к серверу
2025-06-04 19:20:25,433 - INFO - Подключение к БД установлено
2025-06-04 19:20:25,433 - INFO - Успешное подключение к серверу
2025-06-04 19:20:25,565 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:20:25,729 - INFO - Попытка подключения к серверу
2025-06-04 19:20:25,732 - INFO - Подключение к БД установлено
2025-06-04 19:20:25,733 - INFO - Успешное подключение к серверу
2025-06-04 19:20:25,870 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:20:26,479 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:20:26,479 - INFO - Завершение работы приложения
2025-06-04 19:26:18,740 - INFO - Подключение к БД установлено
2025-06-04 19:26:18,740 - INFO - Подключение к БД установлено
2025-06-04 19:26:19,732 - INFO - Попытка подключения к серверу
2025-06-04 19:26:19,739 - INFO - Подключение к БД установлено
2025-06-04 19:26:19,739 - INFO - Успешное подключение к серверу
2025-06-04 19:26:20,550 - INFO - Подключение к БД установлено
2025-06-04 19:26:20,550 - INFO - Генерация запущена для сессии 6
2025-06-04 19:26:26,691 - INFO - Подключение к БД установлено
2025-06-04 19:26:26,691 - INFO - Генерация остановлена
2025-06-04 19:29:27,835 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 19:29:27,835 - INFO - Отключено от сервера при завершении работы
2025-06-04 19:29:27,835 - WARNING - Сервер разорвал соединение
2025-06-04 19:29:27,836 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:29:27,836 - INFO - Завершение работы приложения
2025-06-04 19:33:15,475 - INFO - Подключение к БД установлено
2025-06-04 19:33:15,476 - INFO - Подключение к БД установлено
2025-06-04 19:42:16,761 - INFO - Подключение к БД установлено
2025-06-04 19:42:16,761 - INFO - Подключение к БД установлено
2025-06-04 19:42:17,733 - INFO - Попытка подключения к серверу
2025-06-04 19:42:17,742 - INFO - Подключение к БД установлено
2025-06-04 19:42:17,742 - INFO - Успешное подключение к серверу
2025-06-04 19:42:18,166 - INFO - Подключение к БД установлено
2025-06-04 19:42:18,166 - INFO - Генерация запущена для сессии 7
2025-06-04 19:42:18,900 - INFO - Подключение к БД установлено
2025-06-04 19:42:18,900 - INFO - Генерация остановлена
2025-06-04 19:42:20,279 - INFO - Штатное отключение от сервера
2025-06-04 19:42:20,280 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:42:30,877 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:42:30,877 - INFO - Завершение работы приложения
2025-06-04 19:42:41,308 - INFO - Подключение к БД установлено
2025-06-04 19:42:41,309 - INFO - Подключение к БД установлено
2025-06-04 19:42:43,079 - INFO - Попытка подключения к серверу
2025-06-04 19:42:43,082 - INFO - Подключение к БД установлено
2025-06-04 19:42:43,082 - INFO - Успешное подключение к серверу
2025-06-04 19:42:45,997 - INFO - Штатное отключение от сервера
2025-06-04 19:42:45,998 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:42:59,860 - INFO - Попытка подключения к серверу
2025-06-04 19:42:59,863 - INFO - Подключение к БД установлено
2025-06-04 19:42:59,864 - INFO - Успешное подключение к серверу
2025-06-04 19:43:01,619 - INFO - Штатное отключение от сервера
2025-06-04 19:43:01,619 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:43:01,800 - INFO - Попытка подключения к серверу
2025-06-04 19:43:01,803 - INFO - Подключение к БД установлено
2025-06-04 19:43:01,803 - INFO - Успешное подключение к серверу
2025-06-04 19:43:01,966 - INFO - Штатное отключение от сервера
2025-06-04 19:43:01,967 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:43:02,123 - INFO - Попытка подключения к серверу
2025-06-04 19:43:02,126 - INFO - Подключение к БД установлено
2025-06-04 19:43:02,126 - INFO - Успешное подключение к серверу
2025-06-04 19:43:02,289 - INFO - Штатное отключение от сервера
2025-06-04 19:43:02,290 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:43:03,845 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:43:03,845 - INFO - Завершение работы приложения
2025-06-04 19:43:30,131 - INFO - Подключение к БД установлено
2025-06-04 19:43:30,131 - INFO - Подключение к БД установлено
2025-06-04 19:43:31,559 - INFO - Попытка подключения к серверу
2025-06-04 19:43:31,562 - INFO - Подключение к БД установлено
2025-06-04 19:43:31,562 - INFO - Успешное подключение к серверу
2025-06-04 19:43:32,922 - INFO - Штатное отключение от сервера
2025-06-04 19:43:32,923 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:43:34,087 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:43:34,087 - INFO - Завершение работы приложения
2025-06-04 19:43:39,446 - INFO - Подключение к БД установлено
2025-06-04 19:43:39,446 - INFO - Подключение к БД установлено
2025-06-04 19:43:40,221 - INFO - Попытка подключения к серверу
2025-06-04 19:43:40,224 - INFO - Подключение к БД установлено
2025-06-04 19:43:40,224 - INFO - Успешное подключение к серверу
2025-06-04 19:43:41,152 - INFO - Штатное отключение от сервера
2025-06-04 19:43:41,152 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:43:42,734 - INFO - Попытка подключения к серверу
2025-06-04 19:43:42,737 - INFO - Подключение к БД установлено
2025-06-04 19:43:42,737 - INFO - Успешное подключение к серверу
2025-06-04 19:43:44,045 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 19:43:44,045 - INFO - Отключено от сервера при завершении работы
2025-06-04 19:43:44,046 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:43:44,046 - INFO - Завершение работы приложения
2025-06-04 19:43:57,767 - INFO - Подключение к БД установлено
2025-06-04 19:43:57,767 - INFO - Подключение к БД установлено
2025-06-04 19:43:58,599 - INFO - Попытка подключения к серверу
2025-06-04 19:43:58,603 - INFO - Подключение к БД установлено
2025-06-04 19:43:58,603 - INFO - Успешное подключение к серверу
2025-06-04 19:43:59,997 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:44:03,091 - INFO - Попытка подключения к серверу
2025-06-04 19:44:03,094 - INFO - Подключение к БД установлено
2025-06-04 19:44:03,094 - INFO - Успешное подключение к серверу
2025-06-04 19:44:03,683 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:44:04,309 - INFO - Попытка подключения к серверу
2025-06-04 19:44:04,312 - INFO - Подключение к БД установлено
2025-06-04 19:44:04,312 - INFO - Успешное подключение к серверу
2025-06-04 19:44:04,385 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:44:04,991 - INFO - Попытка подключения к серверу
2025-06-04 19:44:04,994 - INFO - Подключение к БД установлено
2025-06-04 19:44:04,994 - INFO - Успешное подключение к серверу
2025-06-04 19:44:06,225 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:44:10,236 - INFO - Попытка подключения к серверу
2025-06-04 19:44:10,238 - INFO - Подключение к БД установлено
2025-06-04 19:44:10,238 - INFO - Успешное подключение к серверу
2025-06-04 19:44:12,280 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:44:12,982 - INFO - Попытка подключения к серверу
2025-06-04 19:44:12,985 - INFO - Подключение к БД установлено
2025-06-04 19:44:12,985 - INFO - Успешное подключение к серверу
2025-06-04 19:44:15,154 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 19:44:15,886 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 19:44:15,886 - INFO - Завершение работы приложения
2025-06-04 21:04:26,024 - INFO - Подключение к БД установлено
2025-06-04 21:04:26,025 - INFO - Подключение к БД установлено
2025-06-04 21:04:27,342 - INFO - Попытка подключения к серверу
2025-06-04 21:04:27,351 - INFO - Подключение к БД установлено
2025-06-04 21:04:27,351 - INFO - Успешное подключение к серверу
2025-06-04 21:04:28,123 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 21:04:30,614 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 21:04:30,614 - INFO - Завершение работы приложения
2025-06-04 21:08:31,083 - INFO - Подключение к БД установлено
2025-06-04 21:08:31,083 - INFO - Подключение к БД установлено
2025-06-04 21:08:31,888 - INFO - Попытка подключения к серверу
2025-06-04 21:08:31,895 - INFO - Подключение к БД установлено
2025-06-04 21:08:31,895 - INFO - Успешное подключение к серверу
2025-06-04 21:08:33,089 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 21:08:34,312 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 21:08:34,312 - INFO - Завершение работы приложения
2025-06-04 21:13:07,507 - INFO - Подключение к БД установлено
2025-06-04 21:13:07,507 - INFO - Подключение к БД установлено
2025-06-04 21:13:08,458 - INFO - Попытка подключения к серверу
2025-06-04 21:13:08,465 - INFO - Подключение к БД установлено
2025-06-04 21:13:08,465 - INFO - Успешное подключение к серверу
2025-06-04 21:13:09,305 - INFO - Подключение к БД установлено
2025-06-04 21:13:09,305 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 21:13:10,783 - INFO - Попытка подключения к серверу
2025-06-04 21:13:10,787 - INFO - Подключение к БД установлено
2025-06-04 21:13:10,787 - INFO - Успешное подключение к серверу
2025-06-04 21:13:12,212 - INFO - Подключение к БД установлено
2025-06-04 21:13:12,212 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 21:13:27,263 - INFO - Попытка подключения к серверу
2025-06-04 21:13:27,266 - INFO - Подключение к БД установлено
2025-06-04 21:13:27,266 - INFO - Успешное подключение к серверу
2025-06-04 21:13:31,793 - INFO - Подключение к БД установлено
2025-06-04 21:13:31,793 - INFO - Генерация запущена для сессии 8
2025-06-04 21:13:45,522 - INFO - Подключение к БД установлено
2025-06-04 21:13:45,522 - INFO - Генерация остановлена
2025-06-04 21:23:18,996 - INFO - Подключение к БД установлено
2025-06-04 21:23:18,996 - INFO - Подключение к БД установлено
2025-06-04 21:23:23,574 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 21:23:23,574 - INFO - Завершение работы приложения
2025-06-04 21:24:47,733 - INFO - Подключение к БД установлено
2025-06-04 21:24:47,733 - INFO - Подключение к БД установлено
2025-06-04 21:24:49,673 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 21:24:49,674 - INFO - Завершение работы приложения
2025-06-04 21:36:45,494 - INFO - Подключение к БД установлено
2025-06-04 21:36:45,494 - INFO - Подключение к БД установлено
2025-06-04 21:36:47,537 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 21:36:47,537 - INFO - Завершение работы приложения
2025-06-04 21:39:17,062 - INFO - Подключение к БД установлено
2025-06-04 21:39:17,062 - INFO - Подключение к БД установлено
2025-06-04 21:39:18,698 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 21:39:18,698 - INFO - Завершение работы приложения
2025-06-04 21:47:00,825 - INFO - Подключение к БД установлено
2025-06-04 21:47:00,826 - INFO - Подключение к БД установлено
2025-06-04 21:47:05,210 - ERROR - Ошибка подключения: HTTPConnectionPool(host='none', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000025DE00C8C80>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)"))
2025-06-04 21:47:07,614 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 21:47:07,615 - INFO - Завершение работы приложения
2025-06-04 21:57:29,262 - INFO - Подключение к БД установлено
2025-06-04 21:57:29,263 - INFO - Подключение к БД установлено
2025-06-04 21:57:32,562 - ERROR - Ошибка подключения: HTTPConnectionPool(host='none', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F4939E8CE0>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)"))
2025-06-04 22:02:32,681 - INFO - Подключение к БД установлено
2025-06-04 22:02:32,681 - INFO - Подключение к БД установлено
2025-06-04 22:02:36,536 - ERROR - Ошибка подключения: HTTPConnectionPool(host='none', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000015E9A8C8C20>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)"))
2025-06-04 22:02:41,078 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 22:02:41,079 - INFO - Завершение работы приложения
2025-06-04 22:03:38,916 - INFO - Подключение к БД установлено
2025-06-04 22:03:38,916 - INFO - Подключение к БД установлено
2025-06-04 22:03:42,341 - ERROR - Ошибка подключения: HTTPConnectionPool(host='none', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000149C4BE8C20>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)"))
2025-06-04 22:03:44,100 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 22:03:44,100 - INFO - Завершение работы приложения
2025-06-04 22:09:32,726 - INFO - Подключение к БД установлено
2025-06-04 22:09:32,727 - INFO - Подключение к БД установлено
2025-06-04 22:09:35,197 - INFO - Попытка подключения к серверу
2025-06-04 22:09:35,280 - INFO - Подключение к БД установлено
2025-06-04 22:09:35,280 - INFO - Успешное подключение к серверу
2025-06-04 22:09:52,197 - INFO - Подключение к БД установлено
2025-06-04 22:09:52,197 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 22:09:52,197 - WARNING - Сервер разорвал соединение
2025-06-04 22:09:52,198 - INFO - Отключено от сервера при завершении работы
2025-06-04 22:09:52,198 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 22:09:52,198 - INFO - Завершение работы приложения
2025-06-04 22:12:29,476 - INFO - Подключение к БД установлено
2025-06-04 22:12:29,476 - INFO - Подключение к БД установлено
2025-06-04 22:12:34,583 - ERROR - Ошибка подключения: HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FC25208BF0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-06-04 22:12:39,496 - INFO - Попытка подключения к серверу
2025-06-04 22:12:39,532 - INFO - Подключение к БД установлено
2025-06-04 22:12:39,532 - INFO - Успешное подключение к серверу
2025-06-04 22:14:04,178 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-06-04 22:14:04,178 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000001FC25193920> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-06-04 22:14:04,178 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-06-04 22:14:04,179 - INFO - Подключение к БД установлено
2025-06-04 22:14:04,179 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 22:14:04,179 - WARNING - Сервер разорвал соединение
2025-06-04 22:14:04,179 - INFO - Подключение к БД установлено
2025-06-04 22:14:04,180 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 22:14:04,180 - WARNING - Сервер разорвал соединение
2025-06-04 22:14:09,577 - WARNING - Connection closed Connection is already closed.
2025-06-04 22:14:09,577 - INFO - on_reconnect not defined
2025-06-04 22:14:13,681 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=rdgtVbBg51wT5VOunZkS8Q (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FC25193EF0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-06-04 22:15:06,906 - INFO - Попытка подключения к серверу
2025-06-04 22:15:06,941 - INFO - Подключение к БД установлено
2025-06-04 22:15:06,942 - INFO - Успешное подключение к серверу
2025-06-04 22:15:08,009 - INFO - Подключение к БД установлено
2025-06-04 22:15:08,009 - INFO - Генерация запущена для сессии 9
2025-06-04 22:15:46,735 - INFO - Подключение к БД установлено
2025-06-04 22:15:46,735 - INFO - Генерация остановлена
2025-06-04 22:15:48,481 - INFO - Список сессий обновлен, количество: 9
2025-06-04 22:15:49,170 - INFO - Загружено 18 пакетов для сессии 9
2025-06-04 22:15:49,788 - INFO - Для сессии 7 не найдено пакетов
2025-06-04 22:15:49,788 - WARNING - Предупреждение: Для выбранной сессии нет пакетов данных
2025-06-04 22:15:50,163 - INFO - Загружено 7 пакетов для сессии 4
2025-06-04 22:15:50,482 - INFO - Загружено 3 пакетов для сессии 2
2025-06-04 22:15:50,889 - INFO - Загружено 3 пакетов для сессии 6
2025-06-04 22:15:51,178 - INFO - Загружено 18 пакетов для сессии 9
2025-06-04 22:15:52,552 - INFO - Подключение к БД установлено
2025-06-04 22:15:52,553 - INFO - Отключено от сервера при завершении работы
2025-06-04 22:15:52,553 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-04 22:15:52,553 - WARNING - Сервер разорвал соединение
2025-06-04 22:15:52,553 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 22:15:52,553 - INFO - Завершение работы приложения
2025-06-04 22:55:12,795 - INFO - Подключение к БД установлено
2025-06-04 22:55:12,796 - INFO - Подключение к БД установлено
2025-06-04 22:55:19,191 - ERROR - Ошибка подключения: HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F56D08CE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-06-04 22:55:28,630 - INFO - Попытка подключения к серверу
2025-06-04 22:55:28,670 - INFO - Подключение к БД установлено
2025-06-04 22:55:28,670 - INFO - Успешное подключение к серверу
2025-06-04 22:55:30,939 - INFO - Подключение к БД установлено
2025-06-04 22:55:30,940 - INFO - Отключено от сервера по запросу пользователя
2025-06-04 22:55:32,619 - INFO - Подключение к БД закрыто при завершении работы
2025-06-04 22:55:32,619 - INFO - Завершение работы приложения
2025-06-06 12:56:14,967 - INFO - Подключение к БД установлено
2025-06-06 12:56:14,968 - INFO - Подключение к БД установлено
2025-06-06 12:56:17,352 - INFO - Попытка подключения к серверу
2025-06-06 12:56:17,393 - INFO - Подключение к БД установлено
2025-06-06 12:56:17,393 - INFO - Успешное подключение к серверу
2025-06-06 12:56:19,464 - INFO - Подключение к БД установлено
2025-06-06 12:56:19,466 - INFO - Отключено от сервера по запросу пользователя
2025-06-06 12:56:21,555 - INFO - Попытка подключения к серверу
2025-06-06 12:56:21,560 - INFO - Подключение к БД установлено
2025-06-06 12:56:21,560 - INFO - Успешное подключение к серверу
2025-06-06 12:56:22,228 - INFO - Подключение к БД установлено
2025-06-06 12:56:22,228 - INFO - Отключено от сервера по запросу пользователя
2025-06-06 12:56:33,401 - INFO - Подключение к БД закрыто при завершении работы
2025-06-06 12:56:33,401 - INFO - Завершение работы приложения
2025-06-06 17:11:35,506 - INFO - Подключение к БД установлено
2025-06-06 17:11:35,507 - INFO - Подключение к БД установлено
2025-06-06 17:11:37,760 - INFO - Подключение к БД закрыто при завершении работы
2025-06-06 17:11:37,760 - INFO - Завершение работы приложения
2025-06-06 18:38:52,659 - INFO - Подключение к БД установлено
2025-06-06 18:38:52,661 - INFO - Подключение к БД установлено
2025-06-06 18:38:58,554 - ERROR - Ошибка подключения: HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000131828E8D10>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-06-08 22:34:31,902 - INFO - Подключение к БД установлено
2025-06-08 22:34:31,903 - INFO - Подключение к БД установлено
2025-06-08 22:34:34,144 - INFO - Попытка подключения к серверу
2025-06-08 22:34:34,175 - INFO - Подключение к БД установлено
2025-06-08 22:34:34,175 - INFO - Успешное подключение к серверу
2025-06-08 22:34:37,439 - INFO - Подключение к БД установлено
2025-06-08 22:34:37,439 - INFO - Генерация запущена для сессии 11
2025-06-08 22:34:43,939 - INFO - Подключение к БД установлено
2025-06-08 22:34:43,939 - INFO - Генерация остановлена
2025-06-08 22:37:52,090 - INFO - Подключение к БД установлено
2025-06-08 22:37:52,090 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-08 22:37:52,090 - WARNING - Сервер разорвал соединение
2025-06-08 22:37:52,091 - INFO - Отключено от сервера при завершении работы
2025-06-08 22:37:52,091 - INFO - Подключение к БД закрыто при завершении работы
2025-06-08 22:37:52,091 - INFO - Завершение работы приложения
2025-06-08 22:52:48,683 - INFO - Подключение к БД установлено
2025-06-08 22:52:48,683 - INFO - Подключение к БД установлено
2025-06-08 22:52:59,635 - INFO - Попытка подключения к серверу
2025-06-08 22:52:59,642 - INFO - Подключение к БД установлено
2025-06-08 22:52:59,642 - INFO - Успешное подключение к серверу
2025-06-08 22:53:21,393 - INFO - Подключение к БД установлено
2025-06-08 22:53:21,393 - INFO - Генерация запущена для сессии 15
2025-06-08 22:53:23,754 - INFO - Подключение к БД установлено
2025-06-08 22:53:23,755 - INFO - Генерация остановлена
2025-06-08 22:54:22,825 - INFO - Подключение к БД установлено
2025-06-08 22:54:22,825 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-08 22:54:22,825 - WARNING - Сервер разорвал соединение
2025-06-08 22:54:22,825 - INFO - Отключено от сервера при завершении работы
2025-06-08 22:54:22,826 - INFO - Подключение к БД закрыто при завершении работы
2025-06-08 22:54:22,826 - INFO - Завершение работы приложения
2025-06-08 23:00:08,411 - INFO - Подключение к БД установлено
2025-06-08 23:00:08,411 - INFO - Подключение к БД установлено
2025-06-08 23:00:11,908 - INFO - Подключение к БД закрыто при завершении работы
2025-06-08 23:00:11,908 - INFO - Завершение работы приложения
2025-06-08 23:08:25,992 - INFO - Подключение к БД установлено
2025-06-08 23:08:25,992 - INFO - Подключение к БД установлено
2025-06-08 23:08:41,631 - INFO - Попытка подключения к серверу
2025-06-08 23:08:41,639 - INFO - Подключение к БД установлено
2025-06-08 23:08:41,639 - INFO - Успешное подключение к серверу
2025-06-08 23:08:47,515 - INFO - Подключение к БД установлено
2025-06-08 23:08:47,515 - INFO - Генерация запущена для сессии 17
2025-06-08 23:09:00,217 - INFO - Подключение к БД установлено
2025-06-08 23:09:00,217 - INFO - Генерация остановлена
2025-06-08 23:09:02,491 - INFO - Подключение к БД установлено
2025-06-08 23:09:02,491 - INFO - Генерация запущена для сессии 18
2025-06-08 23:09:13,588 - INFO - Подключение к БД установлено
2025-06-08 23:09:13,588 - INFO - Генерация остановлена
2025-06-09 00:57:34,362 - INFO - Подключение к БД установлено
2025-06-09 00:57:34,363 - INFO - Подключение к БД установлено
2025-06-09 00:57:51,863 - INFO - Попытка подключения к серверу
2025-06-09 00:57:51,898 - INFO - Подключение к БД установлено
2025-06-09 00:57:51,899 - INFO - Успешное подключение к серверу
2025-06-09 00:57:54,921 - INFO - Подключение к БД установлено
2025-06-09 00:57:54,921 - INFO - Генерация запущена для сессии 24
2025-06-09 00:58:10,884 - ERROR - Ошибка остановки генерации, код статуса: 415
2025-06-09 00:58:10,884 - WARNING - Предупреждение: Сервер не подтвердил остановку генерации
2025-06-09 00:58:20,929 - INFO - Подключение к БД установлено
2025-06-09 00:58:20,930 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 00:58:20,930 - WARNING - Сервер разорвал соединение
2025-06-09 00:58:20,930 - INFO - Отключено от сервера при завершении работы
2025-06-09 00:58:20,930 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 00:58:20,931 - INFO - Завершение работы приложения
2025-06-09 01:02:32,731 - INFO - Подключение к БД установлено
2025-06-09 01:02:32,731 - INFO - Подключение к БД установлено
2025-06-09 01:02:34,307 - INFO - Попытка подключения к серверу
2025-06-09 01:02:34,366 - INFO - Подключение к БД установлено
2025-06-09 01:02:34,367 - INFO - Успешное подключение к серверу
2025-06-09 01:02:36,597 - INFO - Подключение к БД установлено
2025-06-09 01:02:36,597 - INFO - Генерация запущена для сессии 26
2025-06-09 01:02:45,514 - ERROR - Ошибка остановки генерации, код статуса: 415
2025-06-09 01:02:45,514 - WARNING - Предупреждение: Сервер не подтвердил остановку генерации
2025-06-09 01:02:56,151 - INFO - Подключение к БД установлено
2025-06-09 01:02:56,152 - INFO - Отключено от сервера по запросу пользователя
2025-06-09 01:03:01,526 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 01:03:01,526 - INFO - Завершение работы приложения
2025-06-09 01:05:37,796 - INFO - Подключение к БД установлено
2025-06-09 01:05:37,796 - INFO - Подключение к БД установлено
2025-06-09 01:05:50,136 - INFO - Попытка подключения к серверу
2025-06-09 01:05:50,143 - INFO - Подключение к БД установлено
2025-06-09 01:05:50,144 - INFO - Успешное подключение к серверу
2025-06-09 01:05:51,170 - INFO - Подключение к БД установлено
2025-06-09 01:05:51,170 - INFO - Генерация запущена для сессии 27
2025-06-09 01:06:03,625 - INFO - Подключение к БД установлено
2025-06-09 01:06:03,625 - INFO - Генерация остановлена при завершении работы
2025-06-09 01:06:03,626 - INFO - Подключение к БД установлено
2025-06-09 01:06:03,627 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 01:06:03,627 - WARNING - Сервер разорвал соединение
2025-06-09 01:06:03,627 - INFO - Отключено от сервера при завершении работы
2025-06-09 01:06:03,627 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 01:06:03,627 - INFO - Завершение работы приложения
2025-06-09 01:06:08,490 - INFO - Подключение к БД установлено
2025-06-09 01:06:08,490 - INFO - Подключение к БД установлено
2025-06-09 01:06:14,612 - INFO - Попытка подключения к серверу
2025-06-09 01:06:14,616 - INFO - Подключение к БД установлено
2025-06-09 01:06:14,616 - INFO - Успешное подключение к серверу
2025-06-09 01:06:15,664 - INFO - Подключение к БД установлено
2025-06-09 01:06:15,664 - INFO - Генерация запущена для сессии 28
2025-06-09 01:06:18,612 - INFO - Подключение к БД установлено
2025-06-09 01:06:18,613 - INFO - Генерация остановлена
2025-06-09 01:06:20,373 - INFO - Подключение к БД установлено
2025-06-09 01:06:20,373 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 01:06:20,373 - INFO - Отключено от сервера при завершении работы
2025-06-09 01:06:20,373 - WARNING - Сервер разорвал соединение
2025-06-09 01:06:20,374 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 01:06:20,374 - INFO - Завершение работы приложения
2025-06-09 01:22:32,860 - INFO - Подключение к БД установлено
2025-06-09 01:22:32,860 - INFO - Подключение к БД установлено
2025-06-09 01:22:58,632 - INFO - Попытка подключения к серверу
2025-06-09 01:22:58,637 - INFO - Подключение к БД установлено
2025-06-09 01:22:58,637 - INFO - Успешное подключение к серверу
2025-06-09 01:23:02,337 - ERROR - Ошибка соединения: <signalrcore.messages.completion_message.CompletionMessage object at 0x000001DCADD51B20>
2025-06-09 01:23:02,349 - INFO - Подключение к БД установлено
2025-06-09 01:23:02,349 - INFO - Генерация запущена для сессии 30
2025-06-09 12:57:49,140 - INFO - Подключение к БД установлено
2025-06-09 12:57:49,141 - INFO - Подключение к БД установлено
2025-06-09 12:57:57,065 - INFO - Попытка подключения к серверу
2025-06-09 12:57:57,110 - INFO - Подключение к БД установлено
2025-06-09 12:57:57,110 - INFO - Успешное подключение к серверу
2025-06-09 12:58:01,104 - INFO - Подключение к БД установлено
2025-06-09 12:58:01,105 - INFO - Генерация запущена для сессии 31
2025-06-09 12:58:08,353 - INFO - Подключение к БД установлено
2025-06-09 12:58:08,353 - INFO - Генерация остановлена
2025-06-09 12:58:14,851 - INFO - Подключение к БД установлено
2025-06-09 12:58:14,852 - INFO - Отключено от сервера по запросу пользователя
2025-06-09 12:58:17,215 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 12:58:17,216 - INFO - Завершение работы приложения
2025-06-09 13:00:13,654 - INFO - Подключение к БД установлено
2025-06-09 13:00:13,654 - INFO - Подключение к БД установлено
2025-06-09 13:00:15,330 - INFO - Список сессий обновлен, количество: 31
2025-06-09 13:00:18,377 - INFO - Для сессии 29 не найдено пакетов
2025-06-09 13:00:18,377 - WARNING - Предупреждение: Для выбранной сессии нет пакетов данных
2025-06-09 13:00:19,393 - INFO - Для сессии 30 не найдено пакетов
2025-06-09 13:00:19,393 - WARNING - Предупреждение: Для выбранной сессии нет пакетов данных
2025-06-09 13:00:19,817 - INFO - Для сессии 29 не найдено пакетов
2025-06-09 13:00:19,817 - WARNING - Предупреждение: Для выбранной сессии нет пакетов данных
2025-06-09 13:00:23,044 - INFO - Загружено 2 пакетов для сессии 28
2025-06-09 13:00:23,800 - INFO - Загружено 6 пакетов для сессии 27
2025-06-09 13:00:25,420 - INFO - Загружено 2 пакетов для сессии 28
2025-06-09 13:00:28,303 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 13:00:28,304 - INFO - Завершение работы приложения
2025-06-09 13:13:18,760 - INFO - Подключение к БД установлено
2025-06-09 13:13:18,760 - INFO - Подключение к БД установлено
2025-06-09 13:13:36,985 - INFO - Список сессий обновлен, количество: 31
2025-06-09 13:13:37,751 - INFO - Загружено 3 пакетов для сессии 31
2025-06-09 13:13:39,859 - INFO - Для сессии 7 не найдено пакетов
2025-06-09 13:13:39,859 - WARNING - Предупреждение: Для выбранной сессии нет пакетов данных
2025-06-09 13:13:40,321 - INFO - Загружено 3 пакетов для сессии 6
2025-06-09 13:13:40,824 - INFO - Загружено 18 пакетов для сессии 9
2025-06-09 13:13:44,868 - INFO - Попытка подключения к серверу
2025-06-09 13:13:44,921 - INFO - Подключение к БД установлено
2025-06-09 13:13:44,921 - INFO - Успешное подключение к серверу
2025-06-09 13:13:53,432 - INFO - Подключение к БД установлено
2025-06-09 13:13:53,432 - INFO - Генерация запущена для сессии 32
2025-06-09 13:14:10,575 - INFO - Подключение к БД установлено
2025-06-09 13:14:10,576 - INFO - Генерация остановлена
2025-06-09 13:14:12,968 - INFO - Загружено 18 пакетов для сессии 9
2025-06-09 13:14:12,969 - INFO - Список сессий обновлен, количество: 32
2025-06-09 13:14:13,660 - INFO - Загружено 8 пакетов для сессии 32
2025-06-09 13:16:07,660 - INFO - Подключение к БД установлено
2025-06-09 13:16:07,661 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 13:16:07,661 - WARNING - Сервер разорвал соединение
2025-06-09 13:16:07,661 - INFO - Отключено от сервера при завершении работы
2025-06-09 13:16:07,662 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 13:16:07,662 - INFO - Завершение работы приложения
2025-06-09 13:19:26,252 - INFO - Подключение к БД установлено
2025-06-09 13:19:26,252 - INFO - Подключение к БД установлено
2025-06-09 13:19:42,258 - INFO - Попытка подключения к серверу
2025-06-09 13:19:42,265 - INFO - Подключение к БД установлено
2025-06-09 13:19:42,265 - INFO - Успешное подключение к серверу
2025-06-09 13:19:46,794 - INFO - Подключение к БД установлено
2025-06-09 13:19:46,795 - INFO - Генерация запущена для сессии 33
2025-06-09 13:20:37,645 - INFO - Подключение к БД установлено
2025-06-09 13:20:37,646 - INFO - Генерация остановлена
2025-06-09 13:20:40,454 - INFO - Список сессий обновлен, количество: 34
2025-06-09 13:20:40,873 - INFO - Загружено 3 пакетов для сессии 34
2025-06-09 13:20:42,703 - INFO - Загружено 22 пакетов для сессии 33
2025-06-09 13:20:43,861 - INFO - Загружено 3 пакетов для сессии 34
2025-06-09 13:20:44,791 - INFO - Подключение к БД установлено
2025-06-09 13:20:44,792 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 13:20:44,792 - WARNING - Сервер разорвал соединение
2025-06-09 13:20:44,792 - INFO - Отключено от сервера при завершении работы
2025-06-09 13:20:44,792 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 13:20:44,792 - INFO - Завершение работы приложения
2025-06-09 19:26:41,061 - INFO - Подключение к БД установлено
2025-06-09 19:26:41,062 - INFO - Подключение к БД установлено
2025-06-09 19:26:56,496 - INFO - Попытка подключения к серверу
2025-06-09 19:26:56,504 - INFO - Подключение к БД установлено
2025-06-09 19:26:56,504 - INFO - Успешное подключение к серверу
2025-06-09 19:27:07,514 - INFO - Подключение к БД установлено
2025-06-09 19:27:07,515 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 19:27:07,515 - WARNING - Сервер разорвал соединение
2025-06-09 19:27:07,515 - INFO - Отключено от сервера при завершении работы
2025-06-09 19:27:07,516 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 19:27:07,516 - INFO - Завершение работы приложения
2025-06-09 19:27:49,439 - INFO - Подключение к БД установлено
2025-06-09 19:27:49,439 - INFO - Подключение к БД установлено
2025-06-09 19:27:50,758 - INFO - Попытка подключения к серверу
2025-06-09 19:27:50,762 - INFO - Подключение к БД установлено
2025-06-09 19:27:50,762 - INFO - Успешное подключение к серверу
2025-06-09 19:27:53,600 - INFO - Подключение к БД установлено
2025-06-09 19:27:53,600 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 19:27:53,600 - WARNING - Сервер разорвал соединение
2025-06-09 19:27:53,601 - INFO - Отключено от сервера при завершении работы
2025-06-09 19:27:53,601 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 19:27:53,601 - INFO - Завершение работы приложения
2025-06-09 19:50:55,058 - INFO - Подключение к БД установлено
2025-06-09 19:50:55,059 - INFO - Подключение к БД установлено
2025-06-09 19:50:56,590 - INFO - Попытка подключения к серверу
2025-06-09 19:50:56,632 - INFO - Подключение к БД установлено
2025-06-09 19:50:56,632 - INFO - Успешное подключение к серверу
2025-06-09 19:50:57,707 - INFO - Подключение к БД установлено
2025-06-09 19:50:57,707 - INFO - Генерация запущена для сессии 38
2025-06-09 19:50:59,640 - INFO - Подключение к БД установлено
2025-06-09 19:50:59,640 - INFO - Генерация остановлена
2025-06-09 19:53:12,141 - INFO - Подключение к БД установлено
2025-06-09 19:53:12,141 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 19:53:12,141 - WARNING - Сервер разорвал соединение
2025-06-09 19:53:12,141 - INFO - Отключено от сервера при завершении работы
2025-06-09 19:53:12,142 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 19:53:12,142 - INFO - Завершение работы приложения
2025-06-09 19:53:15,759 - INFO - Подключение к БД установлено
2025-06-09 19:53:15,760 - INFO - Подключение к БД установлено
2025-06-09 19:53:31,005 - INFO - Попытка подключения к серверу
2025-06-09 19:53:31,008 - INFO - Подключение к БД установлено
2025-06-09 19:53:31,008 - INFO - Успешное подключение к серверу
2025-06-09 19:53:34,604 - INFO - Подключение к БД установлено
2025-06-09 19:53:34,605 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 19:53:34,605 - WARNING - Сервер разорвал соединение
2025-06-09 19:53:34,605 - INFO - Отключено от сервера при завершении работы
2025-06-09 19:53:34,605 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 19:53:34,606 - INFO - Завершение работы приложения
2025-06-09 20:32:08,243 - INFO - Подключение к БД установлено
2025-06-09 20:32:08,243 - INFO - Подключение к БД установлено
2025-06-09 20:32:10,532 - INFO - Попытка подключения к серверу
2025-06-09 20:32:10,578 - INFO - Подключение к БД установлено
2025-06-09 20:32:10,578 - INFO - Успешное подключение к серверу
2025-06-09 20:32:12,294 - INFO - Подключение к БД установлено
2025-06-09 20:32:12,294 - INFO - Генерация запущена для сессии 41
2025-06-09 20:35:09,660 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-06-09 20:35:09,661 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x000002C5C46E7A70> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-06-09 20:35:09,661 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-06-09 20:35:09,661 - INFO - Подключение к БД установлено
2025-06-09 20:35:09,661 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 20:35:09,661 - WARNING - Сервер разорвал соединение
2025-06-09 20:35:09,661 - INFO - Подключение к БД установлено
2025-06-09 20:35:09,662 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 20:35:09,662 - WARNING - Сервер разорвал соединение
2025-06-09 20:38:13,848 - INFO - Подключение к БД установлено
2025-06-09 20:38:13,848 - INFO - Подключение к БД установлено
2025-06-09 20:38:15,475 - INFO - Попытка подключения к серверу
2025-06-09 20:38:15,514 - INFO - Подключение к БД установлено
2025-06-09 20:38:15,514 - INFO - Успешное подключение к серверу
2025-06-09 20:38:17,827 - INFO - Подключение к БД установлено
2025-06-09 20:38:17,827 - INFO - Генерация запущена для сессии 42
2025-06-09 20:38:17,827 - INFO - Ответ сервера: {"SessionId": 42}
2025-06-09 20:40:26,967 - ERROR - Traceback (most recent call last):
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 362, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 54, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_app.py", line 328, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 350, in recv_frame
    self.recv_header()
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 306, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_abnf.py", line 385, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_core.py", line 521, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\logos\Desktop\Telemetry\Client\.venv\Lib\site-packages\websocket\_socket.py", line 115, in recv
    bytes_ = _recv()
             ^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

2025-06-09 20:40:26,967 - ERROR - <signalrcore.transport.websockets.websocket_transport.WebsocketTransport object at 0x00000262C60D7AA0> [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2025-06-09 20:40:26,967 - ERROR - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение <class 'ConnectionResetError'>
2025-06-09 20:40:26,967 - INFO - Подключение к БД установлено
2025-06-09 20:40:26,968 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 20:40:26,968 - WARNING - Сервер разорвал соединение
2025-06-09 20:40:26,968 - INFO - Подключение к БД установлено
2025-06-09 20:40:26,968 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 20:40:26,969 - WARNING - Сервер разорвал соединение
2025-06-09 20:40:27,578 - WARNING - Connection closed Connection is already closed.
2025-06-09 20:40:27,578 - INFO - on_reconnect not defined
2025-06-09 20:40:31,667 - ERROR - HTTPConnectionPool(host='localhost', port=15233): Max retries exceeded with url: /telemetryhub/negotiate?id=KgG7TURY9vcY2gSQjkOIIQ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000262C61520C0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
2025-06-09 20:47:09,305 - INFO - Подключение к БД установлено
2025-06-09 20:47:09,305 - INFO - Подключение к БД установлено
2025-06-09 20:47:12,199 - INFO - Попытка подключения к серверу
2025-06-09 20:47:12,235 - INFO - Подключение к БД установлено
2025-06-09 20:47:12,236 - INFO - Успешное подключение к серверу
2025-06-09 20:47:15,761 - INFO - Получен SessionId: 43
2025-06-09 20:47:15,790 - INFO - Ответ на start_generation: 200, {"message":"Генерация данных запущена","sessionId":43}
2025-06-09 20:47:15,790 - INFO - Успешно присоединились к сессии 43
2025-06-09 20:47:15,791 - INFO - Подключение к БД установлено
2025-06-09 20:47:15,791 - INFO - Генерация запущена для сессии 43
2025-06-09 20:47:26,368 - INFO - Подключение к БД установлено
2025-06-09 20:47:26,369 - INFO - Генерация остановлена
2025-06-09 20:47:27,570 - INFO - Список сессий обновлен, количество: 43
2025-06-09 20:47:28,126 - INFO - Загружено 5 пакетов для сессии 43
2025-06-09 20:47:33,501 - INFO - Подключение к БД установлено
2025-06-09 20:47:33,501 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 20:47:33,501 - WARNING - Сервер разорвал соединение
2025-06-09 20:47:33,502 - INFO - Отключено от сервера при завершении работы
2025-06-09 20:47:33,502 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 20:47:33,502 - INFO - Завершение работы приложения
2025-06-09 20:49:00,747 - INFO - Подключение к БД установлено
2025-06-09 20:49:00,748 - INFO - Подключение к БД установлено
2025-06-09 20:49:07,437 - INFO - Попытка подключения к серверу
2025-06-09 20:49:07,444 - INFO - Подключение к БД установлено
2025-06-09 20:49:07,444 - INFO - Успешное подключение к серверу
2025-06-09 20:49:14,779 - INFO - Получен SessionId: 44
2025-06-09 20:49:14,806 - INFO - Ответ на start_generation: 200, {"message":"Генерация данных запущена","sessionId":44}
2025-06-09 20:49:14,806 - INFO - Успешно присоединились к сессии 44
2025-06-09 20:49:14,806 - INFO - Подключение к БД установлено
2025-06-09 20:49:14,806 - INFO - Генерация запущена для сессии 44
2025-06-09 20:49:43,218 - INFO - Подключение к БД установлено
2025-06-09 20:49:43,218 - INFO - Генерация остановлена при завершении работы
2025-06-09 20:49:43,221 - INFO - Подключение к БД установлено
2025-06-09 20:49:43,221 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-09 20:49:43,221 - WARNING - Сервер разорвал соединение
2025-06-09 20:49:43,221 - INFO - Отключено от сервера при завершении работы
2025-06-09 20:49:43,222 - INFO - Подключение к БД закрыто при завершении работы
2025-06-09 20:49:43,222 - INFO - Завершение работы приложения
2025-06-10 13:02:38,487 - INFO - Подключение к БД установлено
2025-06-10 13:02:38,490 - INFO - Подключение к БД установлено
2025-06-10 13:02:42,385 - INFO - Попытка подключения к серверу
2025-06-10 13:02:42,433 - INFO - Подключение к БД установлено
2025-06-10 13:02:42,433 - INFO - Успешное подключение к серверу
2025-06-10 13:02:43,440 - INFO - Получен SessionId: 46
2025-06-10 13:02:43,460 - INFO - Ответ на start_generation: 200, {"message":"Генерация запущена для сессии 46"}
2025-06-10 13:02:43,461 - INFO - Успешно присоединились к сессии 46
2025-06-10 13:02:43,462 - INFO - Подключение к БД установлено
2025-06-10 13:02:43,462 - INFO - Генерация запущена для сессии 46
2025-06-10 13:02:53,748 - ERROR - Ошибка остановки генерации, код статуса: 415
2025-06-10 13:02:53,748 - WARNING - Предупреждение: Сервер не подтвердил остановку генерации
2025-06-10 13:02:56,352 - ERROR - Ошибка остановки генерации, код статуса: 415
2025-06-10 13:02:56,353 - WARNING - Предупреждение: Сервер не подтвердил остановку генерации
2025-06-10 13:03:06,043 - INFO - Подключение к БД установлено
2025-06-10 13:03:06,044 - INFO - Отключено от сервера по запросу пользователя
2025-06-10 13:03:06,446 - WARNING - Connection closed Connection is already closed.
2025-06-10 13:03:06,446 - INFO - on_reconnect not defined
2025-06-10 13:03:06,455 - INFO - Подключение к БД установлено
2025-06-10 13:03:06,456 - INFO - Успешное подключение к серверу
2025-06-10 13:03:09,656 - INFO - Подключение к БД установлено
2025-06-10 13:03:09,656 - INFO - Отключено от сервера по запросу пользователя
2025-06-10 13:03:10,953 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 13:03:10,953 - INFO - Завершение работы приложения
2025-06-10 13:03:30,225 - INFO - Подключение к БД установлено
2025-06-10 13:03:30,225 - INFO - Подключение к БД установлено
2025-06-10 13:03:37,884 - INFO - Попытка подключения к серверу
2025-06-10 13:03:37,919 - INFO - Подключение к БД установлено
2025-06-10 13:03:37,919 - INFO - Успешное подключение к серверу
2025-06-10 13:03:40,768 - INFO - Получен SessionId: 47
2025-06-10 13:03:40,788 - INFO - Ответ на start_generation: 200, {"message":"Генерация запущена для сессии 47"}
2025-06-10 13:03:40,788 - INFO - Успешно присоединились к сессии 47
2025-06-10 13:03:40,789 - INFO - Подключение к БД установлено
2025-06-10 13:03:40,789 - INFO - Генерация запущена для сессии 47
2025-06-10 13:03:45,012 - ERROR - Ошибка остановки генерации, код статуса: 415
2025-06-10 13:03:45,013 - WARNING - Предупреждение: Сервер не подтвердил остановку генерации
2025-06-10 13:22:44,878 - INFO - Подключение к БД установлено
2025-06-10 13:22:44,878 - INFO - Подключение к БД установлено
2025-06-10 13:22:46,171 - INFO - Попытка подключения к серверу
2025-06-10 13:22:46,210 - INFO - Подключение к БД установлено
2025-06-10 13:22:46,210 - INFO - Успешное подключение к серверу
2025-06-10 13:22:48,104 - INFO - Получен SessionId: 48
2025-06-10 13:22:48,125 - INFO - Ответ на start_generation: 200, {"message":"Генерация запущена для сессии 48"}
2025-06-10 13:22:48,125 - INFO - Успешно присоединились к сессии 48
2025-06-10 13:22:48,126 - INFO - Подключение к БД установлено
2025-06-10 13:22:48,126 - INFO - Генерация запущена для сессии 48
2025-06-10 13:51:48,810 - INFO - Подключение к БД установлено
2025-06-10 13:51:48,811 - INFO - Подключение к БД установлено
2025-06-10 13:51:50,314 - INFO - Попытка подключения к серверу
2025-06-10 13:51:50,349 - INFO - Подключение к БД установлено
2025-06-10 13:51:50,349 - INFO - Успешное подключение к серверу
2025-06-10 13:51:51,238 - INFO - Получен SessionId: 49
2025-06-10 13:51:51,257 - INFO - Ответ на start_generation: 200, {"message":"Генерация запущена для сессии 49"}
2025-06-10 13:51:51,258 - INFO - Успешно присоединились к сессии 49
2025-06-10 13:51:51,258 - INFO - Подключение к БД установлено
2025-06-10 13:51:51,258 - INFO - Генерация запущена для сессии 49
2025-06-10 13:52:01,535 - INFO - Подключение к БД установлено
2025-06-10 13:52:01,535 - INFO - Генерация остановлена
2025-06-10 14:05:14,531 - INFO - Подключение к БД установлено
2025-06-10 14:05:14,531 - INFO - Подключение к БД установлено
2025-06-10 14:05:15,366 - INFO - Попытка подключения к серверу
2025-06-10 14:05:15,373 - INFO - Подключение к БД установлено
2025-06-10 14:05:15,373 - INFO - Успешное подключение к серверу
2025-06-10 14:05:15,969 - INFO - Подключение к БД установлено
2025-06-10 14:05:15,969 - INFO - Генерация запущена для сессии 50
2025-06-10 14:05:32,643 - INFO - Подключение к БД установлено
2025-06-10 14:05:32,643 - INFO - Генерация остановлена
2025-06-10 14:05:33,966 - INFO - Подключение к БД установлено
2025-06-10 14:05:33,966 - INFO - Генерация запущена для сессии 51
2025-06-10 14:05:34,981 - INFO - Подключение к БД установлено
2025-06-10 14:05:34,981 - INFO - Генерация остановлена
2025-06-10 14:05:37,116 - INFO - Подключение к БД установлено
2025-06-10 14:05:37,118 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 14:05:37,118 - WARNING - Сервер разорвал соединение
2025-06-10 14:05:37,118 - INFO - Отключено от сервера при завершении работы
2025-06-10 14:05:37,118 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 14:05:37,119 - INFO - Завершение работы приложения
2025-06-10 14:09:22,705 - INFO - Подключение к БД установлено
2025-06-10 14:09:22,705 - INFO - Подключение к БД установлено
2025-06-10 14:09:26,853 - INFO - Попытка подключения к серверу
2025-06-10 14:09:26,887 - INFO - Подключение к БД установлено
2025-06-10 14:09:26,887 - INFO - Успешное подключение к серверу
2025-06-10 14:09:40,685 - INFO - Подключение к БД установлено
2025-06-10 14:09:40,685 - INFO - Генерация запущена для сессии 52
2025-06-10 14:09:56,960 - INFO - Подключение к БД установлено
2025-06-10 14:09:56,960 - INFO - Генерация остановлена
2025-06-10 14:13:21,866 - INFO - Подключение к БД установлено
2025-06-10 14:13:21,866 - INFO - Подключение к БД установлено
2025-06-10 14:13:23,318 - INFO - Список сессий обновлен, количество: 52
2025-06-10 14:13:24,504 - INFO - Загружено 8 пакетов для сессии 52
2025-06-10 14:13:35,612 - INFO - Попытка подключения к серверу
2025-06-10 14:13:35,624 - INFO - Подключение к БД установлено
2025-06-10 14:13:35,624 - INFO - Успешное подключение к серверу
2025-06-10 14:13:37,124 - INFO - Подключение к БД установлено
2025-06-10 14:13:37,124 - INFO - Генерация запущена для сессии 53
2025-06-10 14:13:41,232 - INFO - Подключение к БД установлено
2025-06-10 14:13:41,232 - INFO - Генерация остановлена
2025-06-10 14:14:33,047 - INFO - Подключение к БД установлено
2025-06-10 14:14:33,048 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 14:14:33,048 - WARNING - Сервер разорвал соединение
2025-06-10 14:14:33,048 - INFO - Отключено от сервера при завершении работы
2025-06-10 14:14:33,048 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 14:14:33,049 - INFO - Завершение работы приложения
2025-06-10 14:15:28,674 - INFO - Подключение к БД установлено
2025-06-10 14:15:28,675 - INFO - Подключение к БД установлено
2025-06-10 14:15:29,632 - INFO - Попытка подключения к серверу
2025-06-10 14:15:29,642 - INFO - Подключение к БД установлено
2025-06-10 14:15:29,642 - INFO - Успешное подключение к серверу
2025-06-10 14:15:30,203 - INFO - Подключение к БД установлено
2025-06-10 14:15:30,203 - INFO - Генерация запущена для сессии 54
2025-06-10 14:15:34,475 - INFO - Подключение к БД установлено
2025-06-10 14:15:34,475 - INFO - Генерация остановлена
2025-06-10 14:16:52,519 - INFO - Подключение к БД установлено
2025-06-10 14:16:52,519 - INFO - Подключение к БД установлено
2025-06-10 14:17:01,215 - INFO - Попытка подключения к серверу
2025-06-10 14:17:01,219 - INFO - Подключение к БД установлено
2025-06-10 14:17:01,219 - INFO - Успешное подключение к серверу
2025-06-10 14:17:06,882 - INFO - Подключение к БД установлено
2025-06-10 14:17:06,883 - INFO - Генерация запущена для сессии 58
2025-06-10 14:17:27,638 - INFO - Подключение к БД установлено
2025-06-10 14:17:27,638 - INFO - Генерация остановлена
2025-06-10 14:17:29,153 - INFO - Подключение к БД установлено
2025-06-10 14:17:29,153 - INFO - Генерация запущена для сессии 60
2025-06-10 14:17:39,731 - INFO - Подключение к БД установлено
2025-06-10 14:17:39,731 - INFO - Генерация остановлена
2025-06-10 14:17:43,036 - INFO - Подключение к БД установлено
2025-06-10 14:17:43,036 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 14:17:43,036 - INFO - Отключено от сервера при завершении работы
2025-06-10 14:17:43,037 - WARNING - Сервер разорвал соединение
2025-06-10 14:17:43,037 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 14:17:43,037 - INFO - Завершение работы приложения
2025-06-10 15:24:25,474 - INFO - Подключение к БД установлено
2025-06-10 15:24:25,475 - INFO - Подключение к БД установлено
2025-06-10 15:24:28,131 - INFO - Попытка подключения к серверу
2025-06-10 15:24:28,170 - INFO - Подключение к БД установлено
2025-06-10 15:24:28,170 - INFO - Успешное подключение к серверу
2025-06-10 15:24:30,026 - INFO - Подключение к БД установлено
2025-06-10 15:24:30,027 - INFO - Генерация запущена для сессии 62
2025-06-10 15:24:36,982 - INFO - Подключение к БД установлено
2025-06-10 15:24:36,982 - INFO - Генерация остановлена
2025-06-10 15:25:01,225 - INFO - Подключение к БД установлено
2025-06-10 15:25:01,225 - INFO - Генерация запущена для сессии 64
2025-06-10 15:25:33,650 - INFO - Подключение к БД установлено
2025-06-10 15:25:33,650 - INFO - Генерация остановлена
2025-06-10 15:25:37,569 - INFO - Подключение к БД установлено
2025-06-10 15:25:37,571 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 15:25:37,571 - WARNING - Сервер разорвал соединение
2025-06-10 15:25:37,571 - INFO - Отключено от сервера при завершении работы
2025-06-10 15:25:37,572 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 15:25:37,572 - INFO - Завершение работы приложения
2025-06-10 19:17:15,156 - INFO - Подключение к БД установлено
2025-06-10 19:17:15,157 - INFO - Подключение к БД установлено
2025-06-10 19:17:16,210 - INFO - Попытка подключения к серверу
2025-06-10 19:17:16,256 - INFO - Подключение к БД установлено
2025-06-10 19:17:16,256 - INFO - Успешное подключение к серверу
2025-06-10 19:17:17,744 - INFO - Подключение к БД установлено
2025-06-10 19:17:17,744 - INFO - Генерация запущена для сессии 65
2025-06-10 19:17:20,706 - INFO - Подключение к БД установлено
2025-06-10 19:17:20,706 - INFO - Генерация остановлена
2025-06-10 19:17:36,610 - INFO - Подключение к БД установлено
2025-06-10 19:17:36,611 - INFO - Генерация запущена для сессии 67
2025-06-10 19:17:58,071 - INFO - Подключение к БД установлено
2025-06-10 19:17:58,071 - INFO - Генерация остановлена
2025-06-10 19:18:15,644 - INFO - Подключение к БД установлено
2025-06-10 19:18:15,644 - INFO - Генерация запущена для сессии 68
2025-06-10 19:18:32,474 - INFO - Подключение к БД установлено
2025-06-10 19:18:32,474 - INFO - Генерация остановлена
2025-06-10 19:21:16,370 - INFO - Подключение к БД установлено
2025-06-10 19:21:16,370 - INFO - Генерация запущена для сессии 70
2025-06-10 19:21:20,714 - INFO - Подключение к БД установлено
2025-06-10 19:21:20,714 - INFO - Генерация остановлена
2025-06-10 19:21:23,313 - INFO - Список сессий обновлен, количество: 70
2025-06-10 19:21:23,933 - INFO - Загружено 2 пакетов для сессии 70
2025-06-10 19:21:24,383 - INFO - Загружено 81 пакетов для сессии 69
2025-06-10 19:21:32,636 - INFO - Подключение к БД установлено
2025-06-10 19:21:32,638 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 19:21:32,638 - WARNING - Сервер разорвал соединение
2025-06-10 19:21:32,638 - INFO - Отключено от сервера при завершении работы
2025-06-10 19:21:32,639 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 19:21:32,639 - INFO - Завершение работы приложения
2025-06-10 19:22:22,368 - INFO - Подключение к БД установлено
2025-06-10 19:22:22,369 - INFO - Подключение к БД установлено
2025-06-10 19:22:23,742 - INFO - Попытка подключения к серверу
2025-06-10 19:22:23,786 - INFO - Подключение к БД установлено
2025-06-10 19:22:23,786 - INFO - Успешное подключение к серверу
2025-06-10 19:22:24,754 - INFO - Подключение к БД установлено
2025-06-10 19:22:24,755 - INFO - Генерация запущена для сессии 71
2025-06-10 19:22:37,016 - INFO - Подключение к БД установлено
2025-06-10 19:22:37,017 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 19:22:37,017 - INFO - Отключено от сервера при завершении работы
2025-06-10 19:22:37,017 - WARNING - Сервер разорвал соединение
2025-06-10 19:22:37,017 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 19:22:37,017 - INFO - Завершение работы приложения
2025-06-10 19:33:03,357 - INFO - Подключение к БД установлено
2025-06-10 19:33:03,357 - INFO - Подключение к БД установлено
2025-06-10 19:33:20,329 - INFO - Попытка подключения к серверу
2025-06-10 19:33:20,336 - INFO - Подключение к БД установлено
2025-06-10 19:33:20,337 - INFO - Успешное подключение к серверу
2025-06-10 19:33:28,837 - INFO - Подключение к БД установлено
2025-06-10 19:33:28,837 - INFO - Генерация запущена для сессии 73
2025-06-10 19:34:11,309 - INFO - Подключение к БД установлено
2025-06-10 19:34:11,309 - INFO - Генерация остановлена
2025-06-10 19:34:14,182 - INFO - Подключение к БД установлено
2025-06-10 19:34:14,184 - INFO - Отключено от сервера по запросу пользователя
2025-06-10 19:34:16,532 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 19:34:16,532 - INFO - Завершение работы приложения
2025-06-10 21:00:40,079 - INFO - Подключение к БД установлено
2025-06-10 21:00:40,079 - INFO - Подключение к БД установлено
2025-06-10 21:00:42,309 - INFO - Попытка подключения к серверу
2025-06-10 21:00:42,345 - INFO - Подключение к БД установлено
2025-06-10 21:00:42,346 - INFO - Успешное подключение к серверу
2025-06-10 21:00:44,999 - INFO - Подключение к БД установлено
2025-06-10 21:00:44,999 - INFO - Генерация запущена для сессии 75
2025-06-10 21:01:00,834 - INFO - Подключение к БД установлено
2025-06-10 21:01:00,834 - INFO - Отключено от сервера при завершении работы
2025-06-10 21:01:00,834 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 21:01:00,834 - INFO - Завершение работы приложения
2025-06-10 21:01:07,716 - INFO - Подключение к БД установлено
2025-06-10 21:01:07,716 - INFO - Подключение к БД установлено
2025-06-10 21:01:08,659 - INFO - Попытка подключения к серверу
2025-06-10 21:01:08,663 - INFO - Подключение к БД установлено
2025-06-10 21:01:08,663 - INFO - Успешное подключение к серверу
2025-06-10 21:01:11,192 - INFO - Подключение к БД установлено
2025-06-10 21:01:11,192 - INFO - Генерация запущена для сессии 76
2025-06-10 21:01:22,166 - INFO - Подключение к БД установлено
2025-06-10 21:01:22,166 - INFO - Генерация остановлена
2025-06-10 21:01:23,139 - INFO - Список сессий обновлен, количество: 76
2025-06-10 21:01:23,734 - INFO - Загружено 5 пакетов для сессии 76
2025-06-10 21:01:24,836 - INFO - Загружено 19 пакетов для сессии 75
2025-06-10 21:01:37,908 - INFO - Подключение к БД установлено
2025-06-10 21:01:37,908 - INFO - Генерация запущена для сессии 77
2025-06-10 21:01:40,567 - INFO - Подключение к БД установлено
2025-06-10 21:01:40,567 - INFO - Генерация остановлена
2025-06-10 21:01:47,551 - INFO - Подключение к БД установлено
2025-06-10 21:01:47,552 - INFO - Отключено от сервера по запросу пользователя
2025-06-10 21:01:47,558 - INFO - Восстановлено 1 пропущенных пакетов
2025-06-10 21:01:47,558 - INFO - Подключение к БД установлено
2025-06-10 21:01:47,558 - INFO - Успешное подключение к серверу
2025-06-10 21:01:48,435 - INFO - Попытка подключения к серверу
2025-06-10 21:01:48,438 - INFO - Подключение к БД установлено
2025-06-10 21:01:48,438 - INFO - Успешное подключение к серверу
2025-06-10 21:01:51,208 - INFO - Подключение к БД установлено
2025-06-10 21:01:51,208 - INFO - Генерация запущена для сессии 78
2025-06-10 21:01:52,657 - INFO - Подключение к БД установлено
2025-06-10 21:01:52,657 - INFO - Генерация остановлена
2025-06-10 21:02:14,113 - INFO - Подключение к БД установлено
2025-06-10 21:02:14,113 - INFO - Подключение к БД установлено
2025-06-10 21:02:16,489 - INFO - Попытка подключения к серверу
2025-06-10 21:02:16,493 - INFO - Подключение к БД установлено
2025-06-10 21:02:16,493 - INFO - Успешное подключение к серверу
2025-06-10 21:02:23,771 - INFO - Список сессий обновлен, количество: 78
2025-06-10 21:02:24,216 - INFO - Загружено 1 пакетов для сессии 78
2025-06-10 21:02:25,277 - INFO - Загружено 1 пакетов для сессии 77
2025-06-10 21:02:26,073 - INFO - Загружено 5 пакетов для сессии 76
2025-06-10 21:02:26,649 - INFO - Загружено 4 пакетов для сессии 74
2025-06-10 21:02:28,479 - INFO - Подключение к БД установлено
2025-06-10 21:02:28,479 - INFO - Генерация запущена для сессии 79
2025-06-10 21:02:32,134 - INFO - Подключение к БД установлено
2025-06-10 21:02:32,134 - INFO - Генерация остановлена
2025-06-10 21:02:51,652 - INFO - Подключение к БД установлено
2025-06-10 21:02:51,652 - INFO - Отключено от сервера по запросу пользователя
2025-06-10 21:02:51,659 - INFO - Восстановлено 2 пропущенных пакетов
2025-06-10 21:02:51,659 - INFO - Подключение к БД установлено
2025-06-10 21:02:51,659 - INFO - Успешное подключение к серверу
2025-06-10 21:02:52,524 - WARNING - Connection closed Connection is already closed.
2025-06-10 21:02:52,524 - INFO - on_reconnect not defined
2025-06-10 21:02:52,530 - INFO - Подключение к БД установлено
2025-06-10 21:02:52,530 - INFO - Успешное подключение к серверу
2025-06-10 21:02:52,603 - INFO - Подключение к БД установлено
2025-06-10 21:02:52,603 - INFO - Отключено от сервера при завершении работы
2025-06-10 21:02:52,604 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 21:02:52,604 - INFO - Завершение работы приложения
2025-06-10 21:02:52,610 - INFO - Подключение к БД установлено
2025-06-10 21:02:52,610 - INFO - Успешное подключение к серверу
2025-06-10 21:08:42,528 - INFO - Подключение к БД установлено
2025-06-10 21:08:42,528 - INFO - Подключение к БД установлено
2025-06-10 21:08:43,677 - INFO - Попытка подключения к серверу
2025-06-10 21:08:43,714 - INFO - Подключение к БД установлено
2025-06-10 21:08:43,714 - INFO - Успешное подключение к серверу
2025-06-10 21:08:45,654 - INFO - Подключение к БД установлено
2025-06-10 21:08:45,654 - INFO - Генерация запущена для сессии 80
2025-06-10 21:09:04,918 - INFO - Подключение к БД установлено
2025-06-10 21:09:04,918 - INFO - Отключено от сервера при завершении работы
2025-06-10 21:09:04,919 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 21:09:04,920 - INFO - Завершение работы приложения
2025-06-10 21:09:07,982 - INFO - Подключение к БД установлено
2025-06-10 21:09:07,982 - INFO - Подключение к БД установлено
2025-06-10 21:09:08,965 - INFO - Попытка подключения к серверу
2025-06-10 21:09:08,971 - INFO - Подключение к БД установлено
2025-06-10 21:09:08,971 - INFO - Успешное подключение к серверу
2025-06-10 21:09:11,266 - INFO - Подключение к БД установлено
2025-06-10 21:09:11,266 - INFO - Генерация запущена для сессии 81
2025-06-10 21:09:16,384 - INFO - Список сессий обновлен, количество: 81
2025-06-10 21:09:16,717 - INFO - Загружено 2 пакетов для сессии 81
2025-06-10 21:09:17,359 - INFO - Загружено 15 пакетов для сессии 80
2025-06-10 21:09:19,682 - INFO - Загружено 4 пакетов для сессии 81
2025-06-10 21:09:34,432 - INFO - Подключение к БД установлено
2025-06-10 21:09:34,433 - INFO - Отключено от сервера при завершении работы
2025-06-10 21:09:34,434 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 21:09:34,434 - INFO - Завершение работы приложения
2025-06-10 21:09:34,445 - INFO - Подключение к БД установлено
2025-06-10 21:09:34,445 - INFO - Успешное подключение к серверу
2025-06-10 21:09:34,445 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 21:09:34,446 - WARNING - Сервер разорвал соединение
2025-06-10 21:11:19,243 - INFO - Подключение к БД установлено
2025-06-10 21:11:19,244 - INFO - Подключение к БД установлено
2025-06-10 21:11:20,344 - INFO - Попытка подключения к серверу
2025-06-10 21:11:20,382 - INFO - Подключение к БД установлено
2025-06-10 21:11:20,382 - INFO - Успешное подключение к серверу
2025-06-10 21:11:21,080 - INFO - Подключение к БД установлено
2025-06-10 21:11:21,080 - INFO - Генерация запущена для сессии 82
2025-06-10 21:11:28,475 - INFO - Подключение к БД установлено
2025-06-10 21:11:28,475 - INFO - Генерация остановлена
2025-06-10 21:11:33,298 - INFO - Список сессий обновлен, количество: 82
2025-06-10 21:11:33,831 - INFO - Загружено 4 пакетов для сессии 82
2025-06-10 21:11:34,986 - INFO - Загружено 27 пакетов для сессии 81
2025-06-10 21:11:38,207 - INFO - Подключение к БД установлено
2025-06-10 21:11:38,208 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 21:11:38,208 - WARNING - Сервер разорвал соединение
2025-06-10 21:11:38,208 - INFO - Отключено от сервера при завершении работы
2025-06-10 21:11:38,208 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 21:11:38,209 - INFO - Завершение работы приложения
2025-06-10 23:01:57,677 - INFO - Подключение к БД установлено
2025-06-10 23:01:57,678 - INFO - Подключение к БД установлено
2025-06-10 23:03:03,580 - INFO - Попытка подключения к серверу
2025-06-10 23:03:03,585 - INFO - Подключение к БД установлено
2025-06-10 23:03:03,586 - INFO - Успешное подключение к серверу
2025-06-10 23:03:04,620 - INFO - Подключение к БД установлено
2025-06-10 23:03:04,620 - INFO - Генерация запущена для сессии 84
2025-06-10 23:03:14,011 - INFO - Подключение к БД установлено
2025-06-10 23:03:14,011 - INFO - Генерация остановлена
2025-06-10 23:03:15,648 - INFO - Подключение к БД установлено
2025-06-10 23:03:15,650 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 23:03:15,650 - WARNING - Сервер разорвал соединение
2025-06-10 23:03:15,651 - INFO - Отключено от сервера при завершении работы
2025-06-10 23:03:15,651 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 23:03:15,651 - INFO - Завершение работы приложения
2025-06-10 23:12:52,819 - INFO - Подключение к БД установлено
2025-06-10 23:12:52,819 - INFO - Подключение к БД установлено
2025-06-10 23:12:54,797 - INFO - Попытка подключения к серверу
2025-06-10 23:12:54,838 - INFO - Подключение к БД установлено
2025-06-10 23:12:54,838 - INFO - Успешное подключение к серверу
2025-06-10 23:12:56,360 - INFO - Подключение к БД установлено
2025-06-10 23:12:56,360 - INFO - Генерация запущена для сессии 85
2025-06-10 23:12:59,866 - INFO - Подключение к БД установлено
2025-06-10 23:12:59,866 - INFO - Генерация остановлена
2025-06-10 23:13:00,716 - INFO - Список сессий обновлен, количество: 85
2025-06-10 23:13:02,011 - INFO - Загружено 2 пакетов для сессии 85
2025-06-10 23:13:03,812 - INFO - Подключение к БД установлено
2025-06-10 23:13:03,813 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 23:13:03,813 - INFO - Отключено от сервера при завершении работы
2025-06-10 23:13:03,813 - WARNING - Сервер разорвал соединение
2025-06-10 23:13:03,813 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 23:13:03,813 - INFO - Завершение работы приложения
2025-06-10 23:13:11,710 - INFO - Подключение к БД установлено
2025-06-10 23:13:11,710 - INFO - Подключение к БД установлено
2025-06-10 23:13:12,908 - INFO - Попытка подключения к серверу
2025-06-10 23:13:12,914 - INFO - Подключение к БД установлено
2025-06-10 23:13:12,914 - INFO - Успешное подключение к серверу
2025-06-10 23:13:13,234 - INFO - Подключение к БД установлено
2025-06-10 23:13:13,234 - INFO - Генерация запущена для сессии 86
2025-06-10 23:13:15,821 - INFO - Подключение к БД установлено
2025-06-10 23:13:15,821 - INFO - Генерация остановлена
2025-06-10 23:13:17,006 - INFO - Список сессий обновлен, количество: 86
2025-06-10 23:13:17,517 - INFO - Загружено 2 пакетов для сессии 86
2025-06-10 23:13:20,959 - INFO - Подключение к БД установлено
2025-06-10 23:13:20,960 - WARNING - Предупреждение: Соединение с сервером разорвано
2025-06-10 23:13:20,960 - WARNING - Сервер разорвал соединение
2025-06-10 23:13:20,960 - INFO - Отключено от сервера при завершении работы
2025-06-10 23:13:20,961 - INFO - Подключение к БД закрыто при завершении работы
2025-06-10 23:13:20,961 - INFO - Завершение работы приложения
